In [83]:
import numpy as np
import pandas as pd

In [84]:
df = pd.read_csv (r'MasterDataset_2016_2017_temp.csv')

In [85]:
df.drop(['Placed'],axis='columns', inplace=True)

In [86]:
df

,10thPercentage,12thPercentage,Awards,Branch,CGPA,CTC,CoCurricularActivities,CompanyName,Courses,EmploymentType,...,OtherDetails,ProgLanguages,ProjectDetail,PublicationDetails,Scholarships,SoftwareTools,TierLevel,USN,VolunteeringWork,Workshops
0,96.00,90.00,NaN,CSE,9.68,18.00,NaN,Walmart Labs,"{'Core Courses': [{""{'Code': 'UE15CS101', 'Nam...",NaN,...,"Literature##Sports, Outdoors and Fishing##Educ...",python##c++##c\n,NaN,NaN,NaN,NaN,1.0,01FB15ECS019,NaN,NaN
1,9.70,97.60,Recipient of 6 Distinction Awards in all semes...,CSE,8.83,4.50,NaN,TheMathCompany,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Team member for organizing Atma Trisha in2017,...",C##Python ##Java##HTML ##CSS##PHP##MYSQL.,{Selfieless Photo Sharing App:[Cloud Computing...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,2.0,01FB16ECS002,NaN,NaN
2,9.70,97.60,Recipient of 6 Distinction Awards in all semes...,CSE,8.83,12.15,NaN,NXP Semiconductors,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,"Team member for organizing Atma Trisha in2017,...",C##Python ##Java##HTML ##CSS##PHP##MYSQL.,{Selfieless Photo Sharing App:[Cloud Computing...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,1.0,01FB16ECS002,NaN,NaN
3,95.00,96.00,NaN,CSE,9.27,0.00,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,{Micro-services based website:[ Cloud Computin...,NaN,NaN,NaN,NaN,01FB16ECS006,NaN,NaN
4,NaN,94.00,1st Place at Alcoding Summer Challenge (out of...,CSE,8.95,23.42,NaN,Citrix R&D India Pvt Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Youtube-channel : Algo Made Easy (https://www....,Python##Java##C##JavaScript##HTML##CSS##PHP,{Crio Summer Of Doing:[Data Analytics@@Built a...,NaN,"Prof MRD Scholarship for Academic Excellence, ...",Flask##Spring##MySQL##MongoDB,1.0,01FB16ECS012,NaN,NaN
5,9.40,89.36,NaN,CSE,8.78,8.36,Wildlife#Space#Cricket,Novarties Healthcare PVt. Ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Python# Php# Javascript##CSS## W3.CSS## HTML5#...,{Typing Master:[Web Technology and CloudComput...,NaN,NaN,Web Scraping ## Ajax##Flask##Photoshop## Light...,1.0,01FB16ECS015,NaN,NaN
6,95.00,95.00,Felicitated with Distinction Award for academi...,CSE,9.89,0.00,"Enthusiastic about travelling, photography, re...",Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,C##Python##Java## HTML##CSS##Javascript##PHP,{SelfieLessActs- A cloud based scalable applic...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,NaN,01FB16ECS016,NaN,"Attended workshop on machine learning, image p..."
7,95.00,95.00,Felicitated with Distinction Award for academi...,CSE,9.89,11.59,"Enthusiastic about travelling, photography, re...",Optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##Python##Java## HTML##CSS##Javascript##PHP,{SelfieLessActs- A cloud based scalable applic...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,1.0,01FB16ECS016,NaN,"Attended workshop on machine learning, image p..."
8,94.20,89.20,Bagged 13th rank in “Hour Storm #1” organized ...,CSE,9.39,29.00,NaN,Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Executive Member (Core Team contest organizer)...,C##C++,{Photo-Share:[Cloud Computing@@Built the backe...,"{""Document embedding generation for cyber-aggr...",Recipient of “CNR RAO Merit Scholarship” ##Bag...,SQL,1.0,01FB16ECS017,NaN,NaN
9,94.50,94.50,Awarded First Class with Distinction across al...,CSE,9.04,11.59,NaN,Optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Software development enthusiast.\nAvid learner...,C ##C++##Java ## Python##HTML## CSS##JavaScrip...,{Compiler Design for C:[Compiler Design@@Devel...,NaN,Recipient of Prof CNR RAO Merit Scholarship(20...,NodeJS##Flask,1.0,01FB16ECS018,NaN,NaN
10,9.60,87.20,Bet to Code - Secured Third Position in the co...,CSE,8.57,0.00,An active member of the Center For Innovation ...,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Codechef - Highest Rating of 1603 (handle : ad...,C##Java##Python##C++,{Scheduling ML jobs on distributed systems:[Ma...,"{"" Cassandra - Quality Of Service "":"" Benchmar...",NaN,Cassandra##Spring boot##MongoDB##Mesos##REST,NaN,01FB16ECS023,NaN,L1 CIE
11,95.00,89.40,NaN,CSE,7.71,4.50,Football Player in College Team,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Got 99.41 percentile in e-litmus Aptitude Test...,C##CSS##Python##Java##JavaScript,{Chat Application:[Web Development@@Developed ...,NaN,NaN,Word##Excel##Powerpoint##Angular##Node.js##Exp...,2.0,01FB16ECS031,NaN,NaN
12,94.83,95.80,NaN,CSE,9.90,25.16,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"C++##C##Java,##Python##NodeJS## ReactJS##HTML#...",{Subgraph Isomorphism:[Data Structures and Alg...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN
13,94.83,95.80,NaN,CSE,9.90,NaN,NaN,Intuit,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,"C++##C##Java,##Python##NodeJS## ReactJS##HTML#...",{Subgraph Isomorphism:[Data Structures and Alg...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN
14,10.00,90.60,NaN,CSE,8.68,NaN,NaN,CISCO,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN
15,10.00,90.60,NaN,CSE,8.68,29.00,NaN,Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN
16,8.20,85.60,NaN,CSE,7.30,8.00,NaN,Raramuri Technology Private Limited (website: ...,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##C++##Java##HTML##CSS##Java Script,{SelfieLessActs:[ Cloud Computing@@: A cloud b...,NaN,NaN,NaN,1.0,01FB16ECS037,Organised and volunteered Events of Samarpana.,NaN
17,10.00,95.60,NaN,CSE,9.22,16.00,NaN,Rupeek Fintech Pvt. Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C++##C##Python##R##NodeJS##PHP##HTML##CSS##Jav...,{:[Cloud Computing@@Set up a container orchest...,NaN,NaN,Docker##AWS##GCP##SQL##MongoDB##SailJS##Hadoop...,1.0,01FB16ECS038,NaN,NaN
18,85.60,97.20,NaN,CSE,7.71,6.00,NaN,Enquero Global,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,C##C++##Python##JavaScript##HTML##CSS,{College Project in Web Technologies:[Web Tech...,NaN,NaN,"ReactJS, AWS basics, GCP basics, PostGreSQL, M...",2.0,01FB16ECS044,NaN,NaN
19,91.30,93.80,NaN,CSE,8.64,25.16,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Ranked 390 in Karnataka Common Entrance Test (...,C##C++##Python##Java##HTML##PHP##JavaScript.,{Selfie-less acts website:[Cloud Computing@@ D...,NaN,Received Prof. C N Rao Merit Scholarship durin...,MySQL,1.0,01FB16ECS050,NaN,NaN
20,10.00,90.80,NaN,CSE,9.17,10.35,NaN,AirAsia Technology Centre India Pvt. Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Hindustani Tabla Examination - Junior Level Ka...,C##Python##PHP##HTML##CSS##Javascript##Java,{Selfie-less acts website:[Cloud Computing@@ B...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,1.0,01FB16ECS052,NaN,NaN
21,10.00,90.80,NaN,CSE,9.17,0.00,NaN,LogMeIn,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Hindustani Tabla Examination - Junior Level Ka...,C##Python##PHP##HTML##CSS##Javascript##Java,{Selfie-less acts website:[Cloud Computing@@ B...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,NaN,01FB16ECS052,NaN,NaN
22,NaN,93.00,NaN,CSE,8.98,16.00,NaN,Samsumg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Volleyball captain in school and college##Coor...,C##C++##Python##R##Javascript##Django##OpenCV,{Recommender System:[ Deep Reinforcement Learn...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN
23,NaN,93.00,NaN,CSE,8.98,NaN,NaN,Samsung R&D,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,Volleyball captain in school and college##Coor...,C##C++##Python##R##Javascript##Django##OpenCV,{Recommender System:[ Deep Reinforcement Learn...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN
24,NaN,NaN,NaN,CSE,9.52,16.30,NaN,Akamai Technologies,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS069,NaN,NaN
25,90.00,91.00,NaN,CSE,8.27,0.00,NaN,IBM INDIA PVT LTD,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Stood 3rd in university for ACM-ICPC qualifier...,"C##C++(STL)##Python##JAVA,JS,PHP,",{Web Servlet for Banking:[DBMS@@ Motivation:Fr...,NaN,NaN,Mysql,NaN,01FB16ECS072,NaN,NaN
26,90.00,91.00,NaN,CSE,8.27,12.75,NaN,MathWorks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Stood 3rd in university for ACM-ICPC qualifier...,"C##C++(STL)##Python##JAVA,JS,PHP,",{Web Servlet for Banking:[DBMS@@ Motivation:Fr...,NaN,NaN,Mysql,1.0,01FB16ECS072,NaN,NaN
27,94.88,96.00,NaN,CSE,8.73,8.00,NaN,APMSE Software Services Pvt. Ltd. (EagleView),"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,C##Python ##JAVA,{C++ compiler using lex and yacc:[CD@@ A simpl...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,1.0,01FB16ECS073,NaN,NaN
28,94.88,96.00,NaN,CSE,8.73,6.50,NaN,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##Python ##JAVA,{C++ compiler using lex and yacc:[CD@@ A simpl...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,2.0,01FB16ECS073,NaN,NaN
29,NaN,NaN,Institution of Engineering and Technology (IET...,CSE,9.72,12.75,"President of Mathematics Association 2015-16, ...",MathWorks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Teaching Assistant for Advanced Algorithms, 20...",Python##C##C++## JavaScript,{Youtube Trending Algorithm Analysis:[ML@@ Stu...,{Deep Learning on Binary Patterns for Face Rec...,CNR Rao Merit Scholarship winner for academic ...,Tensorflow##Pytorch##OpenCV##Scikitlearn##Matp...,1.0,01FB16ECS074,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,94.88,92.70,3rd price in Mathematics Fest(Mathletics) held...,CSE,8.93,16.80,NaN,Akamai Technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Introduction to Fast Data Structure L...,{:_},CNR Roa (2),NaN,1.0,PES1201701525,NaN,NaN
164,10.00,97.70,NaN,CSE,9.10,15.00,NaN,Amagi,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Human Activity Captioning:[Project_Hu...,{:_},NaN,NaN,1.0,PES1201701526,NaN,NaN
165,94.16,94.50,Distinction awards in all semesters till date....,CSE,9.31,10.30,NaN,Hewlett Packard Enterprise,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Database as a Service (DBaaS):[Projec...,{Software Implementation of an Automatic Movab...,PROF. M R DORESWAMY MERIT SCHOLARSHIP AWARD\nH...,NaN,1.0,PES1201701528,NaN,Presented my work and submitted a research pap...
166,95.33,93.20,NaN,CSE,8.94,16.87,NaN,Akamai Technologies Pvt Ltd,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Realtime Event Detection using social...,{:_},CNR Rao Scholarship,NaN,1.0,PES1201701532,NaN,NaN
167,98.08,95.50,NaN,CSE,9.29,9.55,NaN,Amadeus Software Labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Restaurant automation system :[Projec...,{:_},"Recipient of CNR Rao Scholarship in the 1st, 3...",NaN,1.0,PES1201701536,Member of CSR (Collegiate Social Responsibility),NaN
168,10.00,96.40,NaN,CSE,9.48,11.00,NaN,Target Corporation India Pvt. Ltd.,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_MongoDB QoS:[Project_MongoDB QoS_Rese...,{:_},NaN,NaN,1.0,PES1201701543,NaN,NaN
169,10.00,95.20,CNR Rao merit scholarship,ECE,8.54,9.55,NaN,Amadeus Software labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,NaN,NaN,{Project_Diabetic Retinopathy Detection using ...,{:_},CNR Rao merit scholarship,NaN,1.0,PES1201701544,NaN,NaN
170,8.20,95.80,NaN,CSE,8.57,25.16,NaN,Intuit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,NaN,NaN,{Project_Cloud Based RideShare Application:[Pr...,{:_},NaN,NaN,1.0,PES1201701545,Core Member for CSR-PESU. Years of Service: 20...,NaN
171,89.00,98.00,Distinction Award for 5 sems,CSE,9.45,27.00,NaN,Curefit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Rideshare API on AWS:[Project_Ridesha...,{:_},CNR Rao Merit Scholarship\nMR Doreswamy Merit ...,NaN,1.0,PES1201701549,NaN,NaN
172,97.28,93.00,NaN,ECE,8.69,20.50,NaN,Analog Devices,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_SELF BALANCING MED-BOT BASED ON INVER...,{:_},CNR and MRD scholarship for 3rd and 5th semest...,NaN,1.0,PES1201701556,Volunteered at The Amateur Scientist Competiti...,"MyCaptain Workshops, PESU-IO on Rocket Propulsion"
173,95.66,91.20,Best Outgoing Student award from BNM Public Sc...,CSE,9.63,18.50,NaN,Amazon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Automatic Questionnaire Generation fr...,{Automatic questionnaire and interactive sessi...,Prof. MRD Merit Scholarship.\nProf CNR Rao Mer...,NaN,1.0,PES1201701573,NaN,NaN
174,95.00,97.20,NaN,CSE,9.38,23.00,NaN,Goldman Sachs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Automated Forensic Artis:[Project_Aut...,{A Paradigmatic Approach to Exploratory Data A...,NaN,NaN,1.0,PES1201701575,NaN,NaN
175,96.00,93.30,NaN,CSE,8.17,22.94,NaN,Citrix,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,• Won ‘Best Debater and Elocutionist Award’ in...,NaN,{Project_Image Completion using DCGAN:[Project...,{:_},NaN,NaN,1.0,PES1201701576,NaN,NaN
176,9.40,96.00,NaN,ECE,6.84,NaN,NaN,NaN,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",NaN,...,NaN,NaN,{Project_Agricultural Automation:[Project_Agri...,{:_},NaN,NaN,NaN,PES1201701579,NaN,An exciting journey of building a $0 - $20 mil...
177,98.88,97.50,Nil,CSE,9.20,5.00,NaN,Robert Bosch Engineering & Business Solutions ...,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Nil,NaN,{Project_Classification of Spectrometric Data:...,{Nil:Nil_Nil},• Obtained MRD & CNR Rao Merit Scholarship for...,NaN,2.0,PES1201701595,Nil,1)Citrix Workshop\n2)FACE Prep Workshop
178,98.24,94.50,NaN,CSE,8.35,7.60,NaN,Deloitte,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Ml-Tool:[Project_Ml-Tool_Machine lean...,{:_},NaN,NaN,2.0,PES1201701597,Part of CSR,NaN
179,10.00,93.00,NaN,ECE,8.81,5.00,NaN,ROBERT BOSCH,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Online Voting System using IPv6 addre...,{”Music Instrument Recognition using Artificia...,CNR Rao Merit Scholarship\nSecured CNR Merit S...,NaN,2.0,PES1201701599,NaN,NaN
180,99.52,97.70,NaN,CSE,9.78,16.90,NaN,Akamai Technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Footballer Market Value prediction:[P...,{:_},NTSE - State Scholar\nCNR Rao Merit Scholarshi...,NaN,1.0,PES1201701604,NaN,NaN
181,10.00,97.20,Distinction award,CSE,9.53,13.96,NaN,Akamai Technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_ Spam Detection in Hotel review using...,{:_},"CNR Scholarship in sem-1,sem-2,sem-3,sem-4,sem-5",NaN,1.0,PES1201701615,NaN,NaN
182,92.00,97.50,NaN,ECE,9.05,14.30,NaN,CISCO,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Electroencephalogram (EEG) signal bas...,{:_},"Received Prof. CNR Rao Merit scholarship""s for...",NaN,1.0,PES1201701617,NaN,NaN
183,9.40,92.20,Recipient of top 20 percentile scholarship and...,ECE,9.06,9.55,NaN,Amadeus Software Labs.,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Hospital management system:[Project_H...,{:_},Recipient of top 20 percentile scholarship and...,NaN,1.0,PES1201701619,NaN,NaN
184,9.80,92.00,NaN,CSE,8.61,10.00,NaN,Epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Efficient Seating Allocation:[Project...,{:_},Prof. CNR Rao scholarship award\nDistinction a...,NaN,1.0,PES1201701621,NaN,NaN
185,99.00,98.20,NaN,CSE,9.77,11.20,NaN,Target India,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_ Research on Recognition of similar h...,{:_},CNR Rao scholarship,NaN,1.0,PES1201701633,NaN,NaN
186,98.24,97.80,NaN,ECE,8.95,10.00,NaN,Epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_FIND INFARCT :[Project_FIND INFARCT _...,{:_},CNR Rao Scholarship For being in top 20% perf...,NaN,1.0,PES1201701648,NaN,NaN
187,9.60,94.20,NaN,ECE,9.04,14.37,NaN,Cisco,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,CET Rank 775,NaN,{Project_A deep learning Image classifier for ...,{:_},Prof. CNR Rao Merit Scholarship: Sem 3\nProf. ...,NaN,1.0,PES1201701651,NaN,Indian Mobile Congress Lead 2019\nConsensus In...
188,98.54,91.80,NaN,CSE,8.50,9.55,NaN,Amadeus Labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,{Project_Big Integer Library :[Project_Big Int...,{:_},Secured Distinction award for top score for al...,NaN,1.0,PES1201701665,NaN,NaN
189,9.60,88.00,"- Prof. CNR Rao Merit Scholarship, PES Univers...",ECE,8.26,5.00,NaN,Robert Bosch,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,NaN,{Project_Smart Shopping Trolley:[Project_Smart...,{:_},NaN,NaN,2.0,PES1201701676,"Teaching Assistant, 2019 - Control Systems, Dr...",Amazon India Technical Workshop : Writing a Cl...
190,94.56,90.50,NaN,EEE,8.07,NaN,NaN,NaN,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",NaN,...,NaN,NaN,{Project_ride share application:[Project_ride ...,{:_},NaN,NaN,NaN,PES1201701751,NaN,NaN
191,95.50,94.70,NaN,CSE,9.45,20.00,NaN,Groww,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,{:_},"Huawei , CNR",NaN,1.0,PES1201701809,NaN,NaN

In [87]:
# 10th percentage and 12 percentage 
# convert everything to percent 10thPercentage, rename 10th marks
# null values -> mean
df['10thMarks'] = 0
df['10thMarks'] = df['10thPercentage'].map(lambda x: float(x)*9.5 if float(x) <=10 else float(x) )
df['10thMarks'].fillna((df['10thMarks'].mean()), inplace=True)
df['12thPercentage'].fillna((df['12thPercentage'].mean()), inplace=True)

In [177]:
df['Awards'].fillna((''),inplace = True)
df['Awards'] = df['Awards'].str.lower()
df['Languages'].fillna((''),inplace = True)
df['ProgLanguages'].fillna((''),inplace = True)

In [89]:
# awards, using keywords to extract

from nltk import ngrams
from sklearn.feature_extraction import text
stop = text.ENGLISH_STOP_WORDS

df["Awards"].apply(lambda words: ' '.join(word.lower() for word in words.split() if word not in stop))

vals = [y for x in df['Awards'] for y in x.split()]

n = [2,3]
a = pd.Series([y for x in n for y in ngrams(vals, x)]).value_counts()
a[:10]

(distinction, award)         14
(award, for)                 11
(in, all)                    10
(distinction, awards)         9
(distinction, award, for)     9
(cnr, rao)                    7
(all, semesters)              6
(with, distinction)           5
(position, in)                4
(in, all, semesters)          4
dtype: int64

In [90]:
#awards AWARDSNLPKEY column will contain only keywords seperated by ##
awards_keywords = ['distinction award','alcoding','hackerearth','olympiad','iisc','outstanding','hackathon','hackerrank','rotary club','iayp','intel','e-yantra','cnr','merit','robotics','machine learning','Data science','olympiad','quiz','microsoft','pesu i/o','centre innovation entrepreneur','model united nation','mun','math','chemistry','outgoing']
df['AwardsNLPkey'] = ''
for key in awards_keywords:
    for i in range(0, len(df)):
        if(df.iloc[i]['Awards'].find(key)!=-1):
            df.iloc[i, df.columns.get_loc('AwardsNLPkey')] =df.iloc[i, df.columns.get_loc('AwardsNLPkey')]+ key+'##'

In [91]:
#finding most occuring languages
pd.Series(' '.join(df['Languages']).lower().replace('\n','').replace(',',"##").replace(' ','##').split('##')).value_counts()[:20]

               289
english        131
hindi          117
kannada         83
telugu          27
tamil           16
malayalam       10
and              7
marathi          7
bengali          6
konkani          5
sanskrit         5
german           4
proficiency      3
)                3
french           2
gujarati         2
(                2
c                2
c+               1
dtype: int64

In [160]:
company_dict = {'Walmart Labs': 'walmart',
'TheMathCompany':'mathcompany',
'NXP Semiconductors': 'nxp',
'Intuit':'intuit',
'Citrix':'citrix',
'Novarties Healthcare':'novarties',
'Raramuri Technology':'raramuri',
'Optum':'optum',
'Cisco Systems':'cisco',
'Accenture':'accenture',
'Rupeek Fintech':'rupeek',
'Enquero Global':'enquero',
'AirAsia Technology Centre':['airasia','air asia'],
'Logmein':'logmein',
'Samsumg':'samsumg',
'Akamai Technologies':'akamai',
'IBM':'ibm',
'Mathworks':'mathworks',
'APMSE Software Services':'ampse',
'Wipro':'wipro',
'LAM Research':'lam',
'Goldman Sachs':'goldman',
'National Instruments':'national instruments',
'Amazon':'amazon',
'App Dynamics':['app dynamics','appdynamics'],
'Societe Generale':'societe',
'Morgan Stanley':'morgan',
'Pluribus Networks':'pluribus',
'Sandvine':'sandvine',
'Microsoft':'microsoft',
'PWC':['pwc','price waterhouse coopers'],
'Commvault':'commvault',
'Cure.Fit':['cure.fit','cure fit'],
'Epsilon':'epsilon',
'Hewlett-Packard Enterprise':['hewlett-packard enterprise','hewlett-packard','hpe','hp','hewlett packard'],
'Zscaler Softech':'zscaler',
'Analog Devices':'analog',
'Target':'target',
'SAP Labs':'sap',
'Gameskraft Technologies':'gameskraft',
'NCR Corporations':'ncr',
'Pensando Systems':'pensando',
'MakeMyTrip':'makemytrip',
'Flipkart':'flipkart',
'Siemens Healthneers':'siemens',
'L&T Technology Services':['l & t technology services','ltts','l&t'],
'Groww':'groww',
'Amagi':'amagi',
'Kickdrum Technologies':'kickdrum',
'SymphonyAI':'symphony',
'Deloitte':'deloitte',
'Cloudera':'cloudera',
'Couchbase':'couchbase',
'Amadeus Software Labs':'amadeus',
'Robert Bosch Engineering & Business Solutions':['bosch','rbei']
}

In [173]:
# making all company names uniform

df['CompanyName']= df['CompanyName'].str.lower()
df['CompanyName_New'] = ''
company_key_list = list(company_dict.keys()) 
company_val_list = list(company_dict.values()) 
for i in range(0, len(df)):
    for j in company_val_list:
        #print(j,type(j))
        if(pd.isnull(df.at[i,'CompanyName'])):
            df.iloc[i, df.columns.get_loc('CompanyName_New')] = np.nan
            #print("nan\n"+j)
            break
        elif(type(j) == str and df.iloc[i]['CompanyName'].find(j)!=-1):
            df.iloc[i, df.columns.get_loc('CompanyName_New')] = company_key_list[company_val_list.index(j)]
            #print('str '+j)
        elif(type(j)==list):
            #print("list outside ",j)
            for k in j:
                if(df.iloc[i]['CompanyName'].find(k)!=-1):
                    df.iloc[i, df.columns.get_loc('CompanyName_New')] = company_key_list[company_val_list.index(j)]
                    #print('list ',j)
                    break

In [174]:
#list(df.CompanyName_New.unique())
df

,10thPercentage,12thPercentage,Awards,Branch,CGPA,CTC,CoCurricularActivities,CompanyName,Courses,EmploymentType,...,PublicationDetails,Scholarships,SoftwareTools,TierLevel,USN,VolunteeringWork,Workshops,10thMarks,AwardsNLPkey,CompanyName_New
0,96.00,90.000000,,CSE,9.68,18.00,NaN,walmart labs,"{'Core Courses': [{""{'Code': 'UE15CS101', 'Nam...",NaN,...,NaN,NaN,NaN,1.0,01FB15ECS019,NaN,NaN,96.000000,,Walmart Labs
1,9.70,97.600000,recipient of 6 distinction awards in all semes...,CSE,8.83,4.50,NaN,themathcompany,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,2.0,01FB16ECS002,NaN,NaN,92.150000,distinction award##,TheMathCompany
2,9.70,97.600000,recipient of 6 distinction awards in all semes...,CSE,8.83,12.15,NaN,nxp semiconductors,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,1.0,01FB16ECS002,NaN,NaN,92.150000,distinction award##,NXP Semiconductors
3,95.00,96.000000,,CSE,9.27,0.00,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,NaN,NaN,01FB16ECS006,NaN,NaN,95.000000,,Intuit
4,NaN,94.000000,1st place at alcoding summer challenge (out of...,CSE,8.95,23.42,NaN,citrix r&d india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"Prof MRD Scholarship for Academic Excellence, ...",Flask##Spring##MySQL##MongoDB,1.0,01FB16ECS012,NaN,NaN,93.386967,alcoding##iisc##,Citrix
5,9.40,89.360000,,CSE,8.78,8.36,Wildlife#Space#Cricket,novarties healthcare pvt. ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,Web Scraping ## Ajax##Flask##Photoshop## Light...,1.0,01FB16ECS015,NaN,NaN,89.300000,,Novarties Healthcare
6,95.00,95.000000,felicitated with distinction award for academi...,CSE,9.89,0.00,"Enthusiastic about travelling, photography, re...",cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,NaN,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",95.000000,distinction award##olympiad##olympiad##math##,Cisco Systems
7,95.00,95.000000,felicitated with distinction award for academi...,CSE,9.89,11.59,"Enthusiastic about travelling, photography, re...",optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,1.0,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",95.000000,distinction award##olympiad##olympiad##math##,Optum
8,94.20,89.200000,bagged 13th rank in “hour storm #1” organized ...,CSE,9.39,29.00,NaN,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"{""Document embedding generation for cyber-aggr...",Recipient of “CNR RAO Merit Scholarship” ##Bag...,SQL,1.0,01FB16ECS017,NaN,NaN,94.200000,hackerearth##,Cisco Systems
9,94.50,94.500000,awarded first class with distinction across al...,CSE,9.04,11.59,NaN,optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Recipient of Prof CNR RAO Merit Scholarship(20...,NodeJS##Flask,1.0,01FB16ECS018,NaN,NaN,94.500000,,Optum
10,9.60,87.200000,bet to code - secured third position in the co...,CSE,8.57,0.00,An active member of the Center For Innovation ...,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,"{"" Cassandra - Quality Of Service "":"" Benchmar...",NaN,Cassandra##Spring boot##MongoDB##Mesos##REST,NaN,01FB16ECS023,NaN,L1 CIE,91.200000,iisc##,Intuit
11,95.00,89.400000,,CSE,7.71,4.50,Football Player in College Team,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,Word##Excel##Powerpoint##Angular##Node.js##Exp...,2.0,01FB16ECS031,NaN,NaN,95.000000,,Accenture
12,94.83,95.800000,,CSE,9.90,25.16,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN,94.830000,,Intuit
13,94.83,95.800000,,CSE,9.90,NaN,NaN,intuit,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN,94.830000,,Intuit
14,10.00,90.600000,,CSE,8.68,NaN,NaN,cisco,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN,95.000000,,Cisco Systems
15,10.00,90.600000,,CSE,8.68,29.00,NaN,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN,95.000000,,Cisco Systems
16,8.20,85.600000,,CSE,7.30,8.00,NaN,raramuri technology private limited (website: ...,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,1.0,01FB16ECS037,Organised and volunteered Events of Samarpana.,NaN,77.900000,,Raramuri Technology
17,10.00,95.600000,,CSE,9.22,16.00,NaN,rupeek fintech pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,Docker##AWS##GCP##SQL##MongoDB##SailJS##Hadoop...,1.0,01FB16ECS038,NaN,NaN,95.000000,,Rupeek Fintech
18,85.60,97.200000,,CSE,7.71,6.00,NaN,enquero global,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,"ReactJS, AWS basics, GCP basics, PostGreSQL, M...",2.0,01FB16ECS044,NaN,NaN,85.600000,,Enquero Global
19,91.30,93.800000,,CSE,8.64,25.16,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Received Prof. C N Rao Merit Scholarship durin...,MySQL,1.0,01FB16ECS050,NaN,NaN,91.300000,,Intuit
20,10.00,90.800000,,CSE,9.17,10.35,NaN,airasia technology centre india pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,1.0,01FB16ECS052,NaN,NaN,95.000000,,AirAsia Technology Centre
21,10.00,90.800000,,CSE,9.17,0.00,NaN,logmein,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,NaN,01FB16ECS052,NaN,NaN,95.000000,,Logmein
22,NaN,93.000000,,CSE,8.98,16.00,NaN,samsumg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,93.386967,,Samsumg
23,NaN,93.000000,,CSE,8.98,NaN,NaN,samsung r&d,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,93.386967,,
24,NaN,92.664813,,CSE,9.52,16.30,NaN,akamai technologies,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,1.0,01FB16ECS069,NaN,NaN,93.386967,,Akamai Technologies
25,90.00,91.000000,,CSE,8.27,0.00,NaN,ibm india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,Mysql,NaN,01FB16ECS072,NaN,NaN,90.000000,,IBM
26,90.00,91.000000,,CSE,8.27,12.75,NaN,mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,Mysql,1.0,01FB16ECS072,NaN,NaN,90.000000,,Mathworks
27,94.88,96.000000,,CSE,8.73,8.00,NaN,apmse software services pvt. ltd. (eagleview),"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,1.0,01FB16ECS073,NaN,NaN,94.880000,,
28,94.88,96.000000,,CSE,8.73,6.50,NaN,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,2.0,01FB16ECS073,NaN,NaN,94.880000,,Accenture
29,NaN,92.664813,institution of engineering and technology (iet...,CSE,9.72,12.75,"President of Mathematics Association 2015-16, ...",mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{Deep Learning on Binary Patterns for Face Rec...,CNR Rao Merit Scholarship winner for academic ...,Tensorflow##Pytorch##OpenCV##Scikitlearn##Matp...,1.0,01FB16ECS074,NaN,NaN,93.386967,outstanding##,Mathworks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,94.88,92.700000,3rd price in mathematics fest(mathletics) held...,CSE,8.93,16.80,NaN,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},CNR Roa (2),NaN,1.0,PES1201701525,NaN,NaN,94.880000,math##,Akamai Technologies
164,10.00,97.700000,,CSE,9.10,15.00,NaN,amagi,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},NaN,NaN,1.0,PES1201701526,NaN,NaN,95.000000,,Amagi
165,94.16,94.500000,distinction awards in all semesters till date....,CSE,9.31,10.30,NaN,hewlett packard enterprise,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{Software Implementation of an Automatic Movab...,PROF. M R DORESWAMY MERIT SCHOLARSHIP AWARD\nH...,NaN,1.0,PES1201701528,NaN,Presented my work and submitted a research pap...,94.160000,distinction award##math##chemistry##,Hewlett-Packard Enterprise
166,95.33,93.200000,,CSE,8.94,16.87,NaN,akamai technologies pvt ltd,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},CNR Rao Scholarship,NaN,1.0,PES1201701532,NaN,NaN,95.330000,,Akamai Technologies
167,98.08,95.500000,,CSE,9.29,9.55,NaN,amadeus software labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},"Recipient of CNR Rao Scholarship in the 1st, 3...",NaN,1.0,PES1201701536,Member of CSR (Collegiate Social Responsibility),NaN,98.080000,,Amadeus Software Labs
168,10.00,96.400000,,CSE,9.48,11.00,NaN,target corporation india pvt. ltd.,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},NaN,NaN,1.0,PES1201701543,NaN,NaN,95.000000,,Target
169,10.00,95.200000,cnr rao merit scholarship,ECE,8.54,9.55,NaN,amadeus software labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,{:_},CNR Rao merit scholarship,NaN,1.0,PES1201701544,NaN,NaN,95.000000,cnr##merit##,Amadeus Software Labs
170,8.20,95.800000,,CSE,8.57,25.16,NaN,intuit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,{:_},NaN,NaN,1.0,PES1201701545,Core Member for CSR-PESU. Years of Service: 20...,NaN,77.900000,,Intuit
171,89.00,98.000000,distinction award for 5 sems,CSE,9.45,27.00,NaN,curefit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},CNR Rao Merit Scholarship\nMR Doreswamy Merit ...,NaN,1.0,PES1201701549,NaN,NaN,89.000000,distinction award##,
172,97.28,93.000000,,ECE,8.69,20.50,NaN,analog devices,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},CNR and MRD scholarship for 3rd and 5th semest...,NaN,1.0,PES1201701556,Volunteered at The Amateur Scientist Competiti...,"MyCaptain Workshops, PESU-IO on Rocket Propulsion",97.280000,,Analog Devices
173,95.66,91.200000,best outgoing student award from bnm public sc...,CSE,9.63,18.50,NaN,amazon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{Automatic questionnaire and interactive sessi...,Prof. MRD Merit Scholarship.\nProf CNR Rao Mer...,NaN,1.0,PES1201701573,NaN,NaN,95.660000,outgoing##,Amazon
174,95.00,97.200000,,CSE,9.38,23.00,NaN,goldman sachs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{A Paradigmatic Approach to Exploratory Data A...,NaN,NaN,1.0,PES1201701575,NaN,NaN,95.000000,,Goldman Sachs
175,96.00,93.300000,,CSE,8.17,22.94,NaN,citrix,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,{:_},NaN,NaN,1.0,PES1201701576,NaN,NaN,96.000000,,Citrix
176,9.40,96.000000,,ECE,6.84,NaN,NaN,NaN,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",NaN,...,{:_},NaN,NaN,NaN,PES1201701579,NaN,An exciting journey of building a $0 - $20 mil...,89.300000,,NaN
177,98.88,97.500000,nil,CSE,9.20,5.00,NaN,robert bosch engineering & business solutions ...,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{Nil:Nil_Nil},• Obtained MRD & CNR Rao Merit Scholarship for...,NaN,2.0,PES1201701595,Nil,1)Citrix Workshop\n2)FACE Prep Workshop,98.880000,,Robert Bosch Engineering & Business Solutions
178,98.24,94.500000,,CSE,8.35,7.60,NaN,deloitte,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},NaN,NaN,2.0,PES1201701597,Part of CSR,NaN,98.240000,,Deloitte
179,10.00,93.000000,,ECE,8.81,5.00,NaN,robert bosch,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{”Music Instrument Recognition using Artificia...,CNR Rao Merit Scholarship\nSecured CNR Merit S...,NaN,2.0,PES1201701599,NaN,NaN,95.000000,,Robert Bosch Engineering & Business Solutions
180,99.52,97.700000,,CSE,9.78,16.90,NaN,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},NTSE - State Scholar\nCNR Rao Merit Scholarshi...,NaN,1.0,PES1201701604,NaN,NaN,99.520000,,Akamai Technologies
181,10.00,97.200000,distinction award,CSE,9.53,13.96,NaN,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},"CNR Scholarship in sem-1,sem-2,sem-3,sem-4,sem-5",NaN,1.0,PES1201701615,NaN,NaN,95.000000,distinction award##,Akamai Technologies
182,92.00,97.500000,,ECE,9.05,14.30,NaN,cisco,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},"Received Prof. CNR Rao Merit scholarship""s for...",NaN,1.0,PES1201701617,NaN,NaN,92.000000,,Cisco Systems
183,9.40,92.200000,recipient of top 20 percentile scholarship and...,ECE,9.06,9.55,NaN,amadeus software labs.,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",Full time employment + Internship (Mandatory),...,{:_},Recipient of top 20 percentile scholarship and...,NaN,1.0,PES1201701619,NaN,NaN,89.300000,distinction award##,Amadeus Software Labs
184,9.80,92.000000,,CSE,8.61,10.00,NaN,epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},Prof. CNR Rao scholarship award\nDistinction a...,NaN,1.0,PES1201701621,NaN,NaN,93.100000,,Epsilon
185,99.00,98.200000,,CSE,9.77,11.20,NaN,target india,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},CNR Rao scholarship,NaN,1.0,PES1201701633,NaN,NaN,99.000000,,Target
186,98.24,97.800000,,ECE,8.95,10.00,NaN,epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},CNR Rao Scholarship For being in top 20% perf...,NaN,1.0,PES1201701648,NaN,NaN,98.240000,,Epsilon
187,9.60,94.200000,,ECE,9.04,14.37,NaN,cisco,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,{:_},Prof. CNR Rao Merit Scholarship: Sem 3\nProf. ...,NaN,1.0,PES1201701651,NaN,Indian Mobile Congress Lead 2019\nConsensus In...,91.200000,,Cisco Systems
188,98.54,91.800000,,CSE,8.50,9.55,NaN,amadeus labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},Secured Distinction award for top score for al...,NaN,1.0,PES1201701665,NaN,NaN,98.540000,,Amadeus Software Labs
189,9.60,88.000000,"- prof. cnr rao merit scholarship, pes univers...",ECE,8.26,5.00,NaN,robert bosch,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},NaN,NaN,2.0,PES1201701676,"Teaching Assistant, 2019 - Control Systems, Dr...",Amazon India Technical Workshop : Writing a Cl...,91.200000,intel##cnr##merit##,Robert Bosch Engineering & Business Solutions
190,94.56,90.500000,,EEE,8.07,NaN,NaN,NaN,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",NaN,...,{:_},NaN,NaN,NaN,PES1201701751,NaN,NaN,94.560000,,NaN
191,95.50,94.700000,,CSE,9.45,20.00,NaN,groww,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{:_},"Huawei , CNR",NaN,1.0,PES1201701809,NaN,NaN,95.500000,,Groww
192,10.00,90.200000,,ECE,7.74,7.60,NaN,deloitte,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,{:_},NaN,NaN,2.0,PES1201702215,NaN,NaN,95.000000,,Deloitte

In [187]:
#finding most occuring programming languages
pd.Series(' '.join(df['ProgLanguages']).lower().replace('\n','').replace(',',"##").replace('.',"##").replace(' ','##').split('##')).value_counts()[:15]

              179
c              41
python         38
javascript     26
java           24
php            21
css            21
html           17
c++            15
r              11
html5           5
language        3
data            3
algorithms      3
handling        3
dtype: int64

In [192]:
#finding most occuring software skills
df['SoftwareTools'].fillna((''),inplace = True)
pd.Series(' '.join(df['SoftwareTools']).lower().replace('\n','').replace(',',"##").replace('.',"##").replace(' ','##').split('##')).value_counts()[:20]

                174
mysql            11
mongodb          10
sql               9
hadoop            9
opencv            7
flask             7
postgresql        6
aws               6
python            6
keras             5
docker            5
gcp               4
tensorflow        4
scikit-learn      4
cloud             3
spring            3
html              3
javascript        3
nltk              3
dtype: int64

In [212]:
#finding most occuring co curricular activities

df['CoCurricularActivities'].fillna((''),inplace = True)
stop = text.ENGLISH_STOP_WORDS
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
df['CoCurricularActivitiesNLP'] = df.CoCurricularActivities.str.replace("[^\w\s]", "").str.lower()

df['CoCurricularActivitiesNLP'] = df['CoCurricularActivitiesNLP'].apply(lambda x: ' '.join([item for item in x.split() if item not in stop]))

vals = [y for x in df['CoCurricularActivitiesNLP'] for y in x.split()]

n = [1]
a = pd.Series([y for x in n for y in ngrams(vals, x)]).value_counts()
a[:20]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rames\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

(club,)              4
(member,)            4
(active,)            3
(social,)            3
(reading,)           2
(csr,)               2
(travelling,)        2
(public,)            2
(collegiate,)        2
(national,)          2
(school,)            2
(responsibility,)    2
(photography,)       2
(college,)           2
(enthusiastic,)      2
(president,)         2
(football,)          1
(technology,)        1
(action,)            1
(201516,)            1
dtype: int64

In [213]:
df

,10thPercentage,12thPercentage,Awards,Branch,CGPA,CTC,CoCurricularActivities,CompanyName,Courses,EmploymentType,...,Scholarships,SoftwareTools,TierLevel,USN,VolunteeringWork,Workshops,10thMarks,AwardsNLPkey,CompanyName_New,CoCurricularActivitiesNLP
0,96.00,90.000000,,CSE,9.68,18.00,,walmart labs,"{'Core Courses': [{""{'Code': 'UE15CS101', 'Nam...",NaN,...,NaN,,1.0,01FB15ECS019,NaN,NaN,96.000000,,Walmart Labs,
1,9.70,97.600000,recipient of 6 distinction awards in all semes...,CSE,8.83,4.50,,themathcompany,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Recipient of CNR Rao Scholarship in the 5th se...,,2.0,01FB16ECS002,NaN,NaN,92.150000,distinction award##,TheMathCompany,
2,9.70,97.600000,recipient of 6 distinction awards in all semes...,CSE,8.83,12.15,,nxp semiconductors,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Recipient of CNR Rao Scholarship in the 5th se...,,1.0,01FB16ECS002,NaN,NaN,92.150000,distinction award##,NXP Semiconductors,
3,95.00,96.000000,,CSE,9.27,0.00,,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,,NaN,01FB16ECS006,NaN,NaN,95.000000,,Intuit,
4,NaN,94.000000,1st place at alcoding summer challenge (out of...,CSE,8.95,23.42,,citrix r&d india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Prof MRD Scholarship for Academic Excellence, ...",Flask##Spring##MySQL##MongoDB,1.0,01FB16ECS012,NaN,NaN,93.386967,alcoding##iisc##,Citrix,
5,9.40,89.360000,,CSE,8.78,8.36,Wildlife#Space#Cricket,novarties healthcare pvt. ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Web Scraping ## Ajax##Flask##Photoshop## Light...,1.0,01FB16ECS015,NaN,NaN,89.300000,,Novarties Healthcare,wildlifespacecricket
6,95.00,95.000000,felicitated with distinction award for academi...,CSE,9.89,0.00,"Enthusiastic about travelling, photography, re...",cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,NaN,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",95.000000,distinction award##olympiad##olympiad##math##,Cisco Systems,enthusiastic travelling photography reading
7,95.00,95.000000,felicitated with distinction award for academi...,CSE,9.89,11.59,"Enthusiastic about travelling, photography, re...",optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,1.0,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",95.000000,distinction award##olympiad##olympiad##math##,Optum,enthusiastic travelling photography reading
8,94.20,89.200000,bagged 13th rank in “hour storm #1” organized ...,CSE,9.39,29.00,,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Recipient of “CNR RAO Merit Scholarship” ##Bag...,SQL,1.0,01FB16ECS017,NaN,NaN,94.200000,hackerearth##,Cisco Systems,
9,94.50,94.500000,awarded first class with distinction across al...,CSE,9.04,11.59,,optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Recipient of Prof CNR RAO Merit Scholarship(20...,NodeJS##Flask,1.0,01FB16ECS018,NaN,NaN,94.500000,,Optum,
10,9.60,87.200000,bet to code - secured third position in the co...,CSE,8.57,0.00,An active member of the Center For Innovation ...,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,Cassandra##Spring boot##MongoDB##Mesos##REST,NaN,01FB16ECS023,NaN,L1 CIE,91.200000,iisc##,Intuit,active member center innovation entrepreneursh...
11,95.00,89.400000,,CSE,7.71,4.50,Football Player in College Team,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Word##Excel##Powerpoint##Angular##Node.js##Exp...,2.0,01FB16ECS031,NaN,NaN,95.000000,,Accenture,football player college team
12,94.83,95.800000,,CSE,9.90,25.16,,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,University merit-based scholarship holder and ...,,1.0,01FB16ECS035,NaN,NaN,94.830000,,Intuit,
13,94.83,95.800000,,CSE,9.90,NaN,,intuit,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,University merit-based scholarship holder and ...,,1.0,01FB16ECS035,NaN,NaN,94.830000,,Intuit,
14,10.00,90.600000,,CSE,8.68,NaN,,cisco,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,,1.0,01FB16ECS036,NaN,NaN,95.000000,,Cisco Systems,
15,10.00,90.600000,,CSE,8.68,29.00,,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,,1.0,01FB16ECS036,NaN,NaN,95.000000,,Cisco Systems,
16,8.20,85.600000,,CSE,7.30,8.00,,raramuri technology private limited (website: ...,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,,1.0,01FB16ECS037,Organised and volunteered Events of Samarpana.,NaN,77.900000,,Raramuri Technology,
17,10.00,95.600000,,CSE,9.22,16.00,,rupeek fintech pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Docker##AWS##GCP##SQL##MongoDB##SailJS##Hadoop...,1.0,01FB16ECS038,NaN,NaN,95.000000,,Rupeek Fintech,
18,85.60,97.200000,,CSE,7.71,6.00,,enquero global,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"ReactJS, AWS basics, GCP basics, PostGreSQL, M...",2.0,01FB16ECS044,NaN,NaN,85.600000,,Enquero Global,
19,91.30,93.800000,,CSE,8.64,25.16,,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Received Prof. C N Rao Merit Scholarship durin...,MySQL,1.0,01FB16ECS050,NaN,NaN,91.300000,,Intuit,
20,10.00,90.800000,,CSE,9.17,10.35,,airasia technology centre india pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Prof. C.N.R. Rao Merit Scholarship,SQL,1.0,01FB16ECS052,NaN,NaN,95.000000,,AirAsia Technology Centre,
21,10.00,90.800000,,CSE,9.17,0.00,,logmein,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Prof. C.N.R. Rao Merit Scholarship,SQL,NaN,01FB16ECS052,NaN,NaN,95.000000,,Logmein,
22,NaN,93.000000,,CSE,8.98,16.00,,samsumg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,93.386967,,Samsumg,
23,NaN,93.000000,,CSE,8.98,NaN,,samsung r&d,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,93.386967,,,
24,NaN,92.664813,,CSE,9.52,16.30,,akamai technologies,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,,1.0,01FB16ECS069,NaN,NaN,93.386967,,Akamai Technologies,
25,90.00,91.000000,,CSE,8.27,0.00,,ibm india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,Mysql,NaN,01FB16ECS072,NaN,NaN,90.000000,,IBM,
26,90.00,91.000000,,CSE,8.27,12.75,,mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Mysql,1.0,01FB16ECS072,NaN,NaN,90.000000,,Mathworks,
27,94.88,96.000000,,CSE,8.73,8.00,,apmse software services pvt. ltd. (eagleview),"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,1.0,01FB16ECS073,NaN,NaN,94.880000,,,
28,94.88,96.000000,,CSE,8.73,6.50,,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,2.0,01FB16ECS073,NaN,NaN,94.880000,,Accenture,
29,NaN,92.664813,institution of engineering and technology (iet...,CSE,9.72,12.75,"President of Mathematics Association 2015-16, ...",mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,CNR Rao Merit Scholarship winner for academic ...,Tensorflow##Pytorch##OpenCV##Scikitlearn##Matp...,1.0,01FB16ECS074,NaN,NaN,93.386967,outstanding##,Mathworks,president mathematics association 201516 natio...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,94.88,92.700000,3rd price in mathematics fest(mathletics) held...,CSE,8.93,16.80,,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,CNR Roa (2),,1.0,PES1201701525,NaN,NaN,94.880000,math##,Akamai Technologies,
164,10.00,97.700000,,CSE,9.10,15.00,,amagi,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,,1.0,PES1201701526,NaN,NaN,95.000000,,Amagi,
165,94.16,94.500000,distinction awards in all semesters till date....,CSE,9.31,10.30,,hewlett packard enterprise,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,PROF. M R DORESWAMY MERIT SCHOLARSHIP AWARD\nH...,,1.0,PES1201701528,NaN,Presented my work and submitted a research pap...,94.160000,distinction award##math##chemistry##,Hewlett-Packard Enterprise,
166,95.33,93.200000,,CSE,8.94,16.87,,akamai technologies pvt ltd,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,CNR Rao Scholarship,,1.0,PES1201701532,NaN,NaN,95.330000,,Akamai Technologies,
167,98.08,95.500000,,CSE,9.29,9.55,,amadeus software labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Recipient of CNR Rao Scholarship in the 1st, 3...",,1.0,PES1201701536,Member of CSR (Collegiate Social Responsibility),NaN,98.080000,,Amadeus Software Labs,
168,10.00,96.400000,,CSE,9.48,11.00,,target corporation india pvt. ltd.,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,,1.0,PES1201701543,NaN,NaN,95.000000,,Target,
169,10.00,95.200000,cnr rao merit scholarship,ECE,8.54,9.55,,amadeus software labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,CNR Rao merit scholarship,,1.0,PES1201701544,NaN,NaN,95.000000,cnr##merit##,Amadeus Software Labs,
170,8.20,95.800000,,CSE,8.57,25.16,,intuit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,NaN,,1.0,PES1201701545,Core Member for CSR-PESU. Years of Service: 20...,NaN,77.900000,,Intuit,
171,89.00,98.000000,distinction award for 5 sems,CSE,9.45,27.00,,curefit,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,CNR Rao Merit Scholarship\nMR Doreswamy Merit ...,,1.0,PES1201701549,NaN,NaN,89.000000,distinction award##,,
172,97.28,93.000000,,ECE,8.69,20.50,,analog devices,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,CNR and MRD scholarship for 3rd and 5th semest...,,1.0,PES1201701556,Volunteered at The Amateur Scientist Competiti...,"MyCaptain Workshops, PESU-IO on Rocket Propulsion",97.280000,,Analog Devices,
173,95.66,91.200000,best outgoing student award from bnm public sc...,CSE,9.63,18.50,,amazon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Prof. MRD Merit Scholarship.\nProf CNR Rao Mer...,,1.0,PES1201701573,NaN,NaN,95.660000,outgoing##,Amazon,
174,95.00,97.200000,,CSE,9.38,23.00,,goldman sachs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,,1.0,PES1201701575,NaN,NaN,95.000000,,Goldman Sachs,
175,96.00,93.300000,,CSE,8.17,22.94,,citrix,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,NaN,,1.0,PES1201701576,NaN,NaN,96.000000,,Citrix,
176,9.40,96.000000,,ECE,6.84,NaN,,NaN,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",NaN,...,NaN,,NaN,PES1201701579,NaN,An exciting journey of building a $0 - $20 mil...,89.300000,,NaN,
177,98.88,97.500000,nil,CSE,9.20,5.00,,robert bosch engineering & business solutions ...,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,• Obtained MRD & CNR Rao Merit Scholarship for...,,2.0,PES1201701595,Nil,1)Citrix Workshop\n2)FACE Prep Workshop,98.880000,,Robert Bosch Engineering & Business Solutions,
178,98.24,94.500000,,CSE,8.35,7.60,,deloitte,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,,2.0,PES1201701597,Part of CSR,NaN,98.240000,,Deloitte,
179,10.00,93.000000,,ECE,8.81,5.00,,robert bosch,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,CNR Rao Merit Scholarship\nSecured CNR Merit S...,,2.0,PES1201701599,NaN,NaN,95.000000,,Robert Bosch Engineering & Business Solutions,
180,99.52,97.700000,,CSE,9.78,16.90,,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NTSE - State Scholar\nCNR Rao Merit Scholarshi...,,1.0,PES1201701604,NaN,NaN,99.520000,,Akamai Technologies,
181,10.00,97.200000,distinction award,CSE,9.53,13.96,,akamai technologies,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"CNR Scholarship in sem-1,sem-2,sem-3,sem-4,sem-5",,1.0,PES1201701615,NaN,NaN,95.000000,distinction award##,Akamai Technologies,
182,92.00,97.500000,,ECE,9.05,14.30,,cisco,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Received Prof. CNR Rao Merit scholarship""s for...",,1.0,PES1201701617,NaN,NaN,92.000000,,Cisco Systems,
183,9.40,92.200000,recipient of top 20 percentile scholarship and...,ECE,9.06,9.55,,amadeus software labs.,"{'Core Courses': [{""{'Code': 'UE16EC357AA', 'N...",Full time employment + Internship (Mandatory),...,Recipient of top 20 percentile scholarship and...,,1.0,PES1201701619,NaN,NaN,89.300000,distinction award##,Amadeus Software Labs,
184,9.80,92.000000,,CSE,8.61,10.00,,epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Prof. CNR Rao scholarship award\nDistinction a...,,1.0,PES1201701621,NaN,NaN,93.100000,,Epsilon,
185,99.00,98.200000,,CSE,9.77,11.20,,target india,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,CNR Rao scholarship,,1.0,PES1201701633,NaN,NaN,99.000000,,Target,
186,98.24,97.800000,,ECE,8.95,10.00,,epsilon,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,CNR Rao Scholarship For being in top 20% perf...,,1.0,PES1201701648,NaN,NaN,98.240000,,Epsilon,
187,9.60,94.200000,,ECE,9.04,14.37,,cisco,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Internship only,...,Prof. CNR Rao Merit Scholarship: Sem 3\nProf. ...,,1.0,PES1201701651,NaN,Indian Mobile Congress Lead 2019\nConsensus In...,91.200000,,Cisco Systems,
188,98.54,91.800000,,CSE,8.50,9.55,,amadeus labs,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Secured Distinction award for top score for al...,,1.0,PES1201701665,NaN,NaN,98.540000,,Amadeus Software Labs,
189,9.60,88.000000,"- prof. cnr rao merit scholarship, pes univers...",ECE,8.26,5.00,,robert bosch,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,,2.0,PES1201701676,"Teaching Assistant, 2019 - Control Systems, Dr...",Amazon India Technical Workshop : Writing a Cl...,91.200000,intel##cnr##merit##,Robert Bosch Engineering & Business Solutions,
190,94.56,90.500000,,EEE,8.07,NaN,,NaN,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",NaN,...,NaN,,NaN,PES1201701751,NaN,NaN,94.560000,,NaN,
191,95.50,94.700000,,CSE,9.45,20.00,,groww,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Huawei , CNR",,1.0,PES1201701809,NaN,NaN,95.500000,,Groww,
192,10.00,90.200000,,ECE,7.74,7.60,,deloitte,"{'Core Courses': [{""{'Code': 'UE17CS101', 'Nam...",Full time employment only,...,NaN,,2.0,PES1201702215,NaN,NaN,95.000000,,Deloitte,