In [24]:
import numpy as np
import pandas as pd
import nltk

In [9]:
df = pd.read_csv (r'C:\Users\diyas\Documents\Recommendation_system\UpdatedMaster19Feb.csv')

In [11]:
df.drop(['Unnamed: 0'],axis='columns', inplace=True)

In [12]:
df

,10thPercentage,12thPercentage,Awards,Branch,CGPA,CTC,CoCurricularActivities,CompanyName,Courses,EmploymentType,...,OtherDetails,ProgLanguages,ProjectDetail,PublicationDetails,Scholarships,SoftwareTools,TierLevel,USN,VolunteeringWork,Workshops
0,96.0,90.0,NaN,CSE,9.68,18.00,NaN,Walmart Labs,"{'Core Courses': [{""{'Code': 'UE15CS101', 'Nam...",NaN,...,"Literature##Sports, Outdoors and Fishing##Educ...",python##c++##c\n,NaN,NaN,NaN,NaN,1.0,01FB15ECS019,NaN,NaN
1,9.7,97.6,Recipient of 6 Distinction Awards in all semes...,CSE,8.83,4.50,NaN,TheMathCompany,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Team member for organizing Atma Trisha in2017,...",C##Python ##Java##HTML ##CSS##PHP##MYSQL.,{Selfieless Photo Sharing App:[Cloud Computing...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,2.0,01FB16ECS002,NaN,NaN
2,9.7,97.6,Recipient of 6 Distinction Awards in all semes...,CSE,8.83,12.15,NaN,NXP Semiconductors,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,"Team member for organizing Atma Trisha in2017,...",C##Python ##Java##HTML ##CSS##PHP##MYSQL.,{Selfieless Photo Sharing App:[Cloud Computing...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,1.0,01FB16ECS002,NaN,NaN
3,95.0,96.0,NaN,CSE,9.27,0.00,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,{Micro-services based website:[ Cloud Computin...,NaN,NaN,NaN,NaN,01FB16ECS006,NaN,NaN
4,NaN,94.0,1st Place at Alcoding Summer Challenge (out of...,CSE,8.95,23.42,NaN,Citrix R&D India Pvt Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Youtube-channel : Algo Made Easy (https://www....,Python##Java##C##JavaScript##HTML##CSS##PHP,{Crio Summer Of Doing:[Data Analytics@@Built a...,NaN,"Prof MRD Scholarship for Academic Excellence, ...",Flask##Spring##MySQL##MongoDB,1.0,01FB16ECS012,NaN,NaN
5,9.4,89.36,NaN,CSE,8.78,8.36,Wildlife#Space#Cricket,Novarties Healthcare PVt. Ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Python# Php# Javascript##CSS## W3.CSS## HTML5#...,{Typing Master:[Web Technology and CloudComput...,NaN,NaN,Web Scraping ## Ajax##Flask##Photoshop## Light...,1.0,01FB16ECS015,NaN,NaN
6,95.0,95.0,Felicitated with Distinction Award for academi...,CSE,9.89,0.00,"Enthusiastic about travelling, photography, re...",Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,C##Python##Java## HTML##CSS##Javascript##PHP,{SelfieLessActs- A cloud based scalable applic...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,NaN,01FB16ECS016,NaN,"Attended workshop on machine learning, image p..."
7,95.0,95.0,Felicitated with Distinction Award for academi...,CSE,9.89,11.59,"Enthusiastic about travelling, photography, re...",Optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##Python##Java## HTML##CSS##Javascript##PHP,{SelfieLessActs- A cloud based scalable applic...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,1.0,01FB16ECS016,NaN,"Attended workshop on machine learning, image p..."
8,94.2,89.2,Bagged 13th rank in “Hour Storm #1” organized ...,CSE,9.39,29.00,NaN,Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Executive Member (Core Team contest organizer)...,C##C++,{Photo-Share:[Cloud Computing@@Built the backe...,"{""Document embedding generation for cyber-aggr...",Recipient of “CNR RAO Merit Scholarship” ##Bag...,SQL,1.0,01FB16ECS017,NaN,NaN
9,94.5,94.5,Awarded First Class with Distinction across al...,CSE,9.04,11.59,NaN,Optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Software development enthusiast.\nAvid learner...,C ##C++##Java ## Python##HTML## CSS##JavaScrip...,{Compiler Design for C:[Compiler Design@@Devel...,NaN,Recipient of Prof CNR RAO Merit Scholarship(20...,NodeJS##Flask,1.0,01FB16ECS018,NaN,NaN
10,9.6,87.2,Bet to Code - Secured Third Position in the co...,CSE,8.57,0.00,An active member of the Center For Innovation ...,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Codechef - Highest Rating of 1603 (handle : ad...,C##Java##Python##C++,{Scheduling ML jobs on distributed systems:[Ma...,"{"" Cassandra - Quality Of Service "":"" Benchmar...",NaN,Cassandra##Spring boot##MongoDB##Mesos##REST,NaN,01FB16ECS023,NaN,L1 CIE
11,95.0,89.4,NaN,CSE,7.71,4.50,Football Player in College Team,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Got 99.41 percentile in e-litmus Aptitude Test...,C##CSS##Python##Java##JavaScript,{Chat Application:[Web Development@@Developed ...,NaN,NaN,Word##Excel##Powerpoint##Angular##Node.js##Exp...,2.0,01FB16ECS031,NaN,NaN
12,94.83,95.8,NaN,CSE,9.90,25.16,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"C++##C##Java,##Python##NodeJS## ReactJS##HTML#...",{Subgraph Isomorphism:[Data Structures and Alg...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN
13,94.83,95.8,NaN,CSE,9.90,NaN,NaN,Intuit,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,"C++##C##Java,##Python##NodeJS## ReactJS##HTML#...",{Subgraph Isomorphism:[Data Structures and Alg...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN
14,10.0,90.6,NaN,CSE,8.68,NaN,NaN,CISCO,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN
15,10.0,90.6,NaN,CSE,8.68,29.00,NaN,Cisco Systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN
16,8.2,85.6,NaN,CSE,7.30,8.00,NaN,Raramuri Technology Private Limited (website: ...,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##C++##Java##HTML##CSS##Java Script,{SelfieLessActs:[ Cloud Computing@@: A cloud b...,NaN,NaN,NaN,1.0,01FB16ECS037,Organised and volunteered Events of Samarpana.,NaN
17,10.0,95.6,NaN,CSE,9.22,16.00,NaN,Rupeek Fintech Pvt. Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C++##C##Python##R##NodeJS##PHP##HTML##CSS##Jav...,{:[Cloud Computing@@Set up a container orchest...,NaN,NaN,Docker##AWS##GCP##SQL##MongoDB##SailJS##Hadoop...,1.0,01FB16ECS038,NaN,NaN
18,85.6,97.2,NaN,CSE,7.71,6.00,NaN,Enquero Global,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,C##C++##Python##JavaScript##HTML##CSS,{College Project in Web Technologies:[Web Tech...,NaN,NaN,"ReactJS, AWS basics, GCP basics, PostGreSQL, M...",2.0,01FB16ECS044,NaN,NaN
19,91.3,93.8,NaN,CSE,8.64,25.16,NaN,Intuit India Product Development Center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Ranked 390 in Karnataka Common Entrance Test (...,C##C++##Python##Java##HTML##PHP##JavaScript.,{Selfie-less acts website:[Cloud Computing@@ D...,NaN,Received Prof. C N Rao Merit Scholarship durin...,MySQL,1.0,01FB16ECS050,NaN,NaN
20,10.0,90.8,NaN,CSE,9.17,10.35,NaN,AirAsia Technology Centre India Pvt. Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Hindustani Tabla Examination - Junior Level Ka...,C##Python##PHP##HTML##CSS##Javascript##Java,{Selfie-less acts website:[Cloud Computing@@ B...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,1.0,01FB16ECS052,NaN,NaN
21,10.0,90.8,NaN,CSE,9.17,0.00,NaN,LogMeIn,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Hindustani Tabla Examination - Junior Level Ka...,C##Python##PHP##HTML##CSS##Javascript##Java,{Selfie-less acts website:[Cloud Computing@@ B...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,NaN,01FB16ECS052,NaN,NaN
22,NaN,93.0,NaN,CSE,8.98,16.00,NaN,Samsumg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Volleyball captain in school and college##Coor...,C##C++##Python##R##Javascript##Django##OpenCV,{Recommender System:[ Deep Reinforcement Learn...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN
23,NaN,93.0,NaN,CSE,8.98,NaN,NaN,Samsung R&D,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,Volleyball captain in school and college##Coor...,C##C++##Python##R##Javascript##Django##OpenCV,{Recommender System:[ Deep Reinforcement Learn...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN
24,NaN,NaN,NaN,CSE,9.52,16.30,NaN,Akamai Technologies,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,01FB16ECS069,NaN,NaN
25,90.0,91.0,NaN,CSE,8.27,0.00,NaN,IBM INDIA PVT LTD,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,Stood 3rd in university for ACM-ICPC qualifier...,"C##C++(STL)##Python##JAVA,JS,PHP,",{Web Servlet for Banking:[DBMS@@ Motivation:Fr...,NaN,NaN,Mysql,NaN,01FB16ECS072,NaN,NaN
26,90.0,91.0,NaN,CSE,8.27,12.75,NaN,MathWorks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Stood 3rd in university for ACM-ICPC qualifier...,"C##C++(STL)##Python##JAVA,JS,PHP,",{Web Servlet for Banking:[DBMS@@ Motivation:Fr...,NaN,NaN,Mysql,1.0,01FB16ECS072,NaN,NaN
27,94.88,96.0,NaN,CSE,8.73,8.00,NaN,APMSE Software Services Pvt. Ltd. (EagleView),"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,C##Python ##JAVA,{C++ compiler using lex and yacc:[CD@@ A simpl...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,1.0,01FB16ECS073,NaN,NaN
28,94.88,96.0,NaN,CSE,8.73,6.50,NaN,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,C##Python ##JAVA,{C++ compiler using lex and yacc:[CD@@ A simpl...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,2.0,01FB16ECS073,NaN,NaN
29,NaN,NaN,Institution of Engineering and Technology (IET...,CSE,9.72,12.75,"President of Mathematics Association 2015-16, ...",MathWorks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"Teaching Assistant for Advanced Algorithms, 20...",Python##C##C++## JavaScript,{Youtube Trending Algorithm Analysis:[ML@@ Stu...,{Deep Learning on Binary Patterns for Face Rec...,CNR Rao Merit Scholarship winner for academic ...,Tensorflow##Pytorch##OpenCV##Scikitlearn##Matp...,1.0,01FB16ECS074,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,NaN,0.896,NaN,CSE,8.36,0.00,NaN,GE Healthcare,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[ C## C++##Python],{Project_1:[Project_1_Domain@@Project_1_ Gener...,NaN,NaN,HTML#### CSS#### Javascript#### SQL,NaN,01FB16ECS440,NaN,NaN
412,NaN,0.896,NaN,CSE,8.36,6.50,NaN,Wipro Turbo,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[ C## C++##Python],{Project_1:[Project_1_Domain@@Project_1_ Gener...,NaN,NaN,HTML#### CSS#### Javascript#### SQL,2.0,01FB16ECS440,NaN,NaN
413,0.903,0.943,NaN,CSE,8.31,8.36,NaN,PwC India,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[Proficient with C & Py thon.],{Project_1:[Project_1_Domain@@Project_1_Websit...,NaN,NaN,"HTML####CSS####Javascript####PHP####,MYSQL",1.0,01FB16ECS441,NaN,"Computer Network Securit y - Wireshark, Kali L..."
414,9.8,85.4,1. 3 live applications on play-store (two game...,CSE,8.18,12.43,NaN,Adobe Systems India Pvt Ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[ Python ## C ## Java],{Project_1:[Project_1_Domain@@Project_1_Self-L...,"Mr. Vinay,\nFounder & CxO,\nPiRuby, Bengaluru",NaN,"Cloud, Machine Learning, Big Data, Android, Un...",1.0,01FB16ECS444,NaN,NaN
415,9.8,85.4,1. 3 live applications on play-store (two game...,CSE,8.18,0.00,NaN,Citrix R&D India Pvt Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[ Python ## C ## Java],{Project_1:[Project_1_Domain@@Project_1_Self-L...,"Mr. Vinay,\nFounder & CxO,\nPiRuby, Bengaluru",NaN,"Cloud, Machine Learning, Big Data, Android, Un...",NaN,01FB16ECS444,NaN,NaN
416,0.9264,0.9675,NaN,CSE,7.74,7.00,NaN,Perfios,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Travelling\n● Cricket\n● Photography\n● Volley...,[],{Project_1:[Project_1_Domain@@Project_1_Generi...,NaN,NaN,NaN,2.0,01FB16ECS446,NaN,NaN
417,NaN,NaN,Awarded with multiple Distinction Certificate,CSE,7.48,7.00,NaN,Perfios,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,[],{Project_1:[Project_1_Domain@@Project_1_ DataB...,NaN,NaN,NaN,2.0,01FB16ECS448,NaN,NaN
418,94,92.4,Awarded Prof. CNR Rao Merit Scholarship for ac...,CSE,9.48,0.00,NaN,Morgan Stanley,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[Python ## C/C++ ## JS ## HTML ## CSS ##PHP ## R],{Project_1:[Project_1_Domain@@Project_1_Analys...,NaN,NaN,NaN,NaN,01FB16ECS456,NaN,NaN
419,94,92.4,Awarded Prof. CNR Rao Merit Scholarship for ac...,CSE,9.48,12.43,NaN,Adobe Systems India Pvt Ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[Python ## C/C++ ## JS ## HTML ## CSS ##PHP ## R],{Project_1:[Project_1_Domain@@Project_1_Analys...,NaN,NaN,NaN,1.0,01FB16ECS456,NaN,NaN
420,0.9536,0.975,NaN,CSE,9.06,0.00,NaN,Amazon,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[C##Python##\nWeb Development : HTML##CSS## Ja...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,NaN,SQLite####Postgres#### MongoDB,NaN,01FB16ECS459,NaN,NaN
421,0.9536,0.975,NaN,CSE,9.06,10.30,NaN,Hewlett Packard Enterprise,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[C##Python##\nWeb Development : HTML##CSS## Ja...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,NaN,SQLite####Postgres#### MongoDB,1.0,01FB16ECS459,NaN,NaN
422,0.9536,0.975,NaN,CSE,9.06,NaN,NaN,HPE,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,[C##Python##\nWeb Development : HTML##CSS## Ja...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,NaN,SQLite####Postgres#### MongoDB,1.0,01FB16ECS459,NaN,NaN
423,CGPA – 8.8,0.8,"Organizer, Samarasa, cultural fest, - Managed...",CSE,7.68,6.00,NaN,ABB Global Industries And Services Pvt Ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[C##C++## Python],{Project_1:[Project_1_Domain@@Project_1_Word E...,● ICACCI 2019\n● Sketch to images using CNN an...,NaN,"MATLAB, TensorFlow, Keras\nWeb Applications: H...",2.0,01FB16ECS461,NaN,MEMBERSHIPS: IEEE Student Member- Responsible ...
424,NaN,NaN,NaN,CSE,7.71,6.50,NaN,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,Reading books\nFootball,[C Programming##\n##R Programming\n##Python Pr...,{Project_1:[Project_1_Domain@@Project_1_Food R...,NaN,NaN,NaN,2.0,01FB16ECS467,NaN,NaN
425,CGPA- 8.0,0.79,Recipient of Distinction Scholarship in 2nd an...,CSE,8.13,4.00,NaN,KPMG,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Technical -Machine Learning\nDatabase Manageme...,[C## C++## Python],{Project_1:[Project_1_Domain@@Project_1_ Mach...,NaN,NaN,"Front-end: HTML, CSS, JavaScript####\nBack-end...",3.0,01FB16ECS468,NaN,NaN
426,8.8,80,NaN,CSE,7.09,3.60,National level Basket Ball gold medalist\nPlay...,DXC Technology,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[],{Project_1:[Project_1_Domain@@Project_1_1. Bui...,NaN,NaN,NaN,3.0,01FB16ECS472,NaN,NaN
427,0.95,0.86,NaN,CSE,7.52,0.00,DEBSOC(DEBATING SOCIETY) General Speaker | 201...,McAfee,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[],{Project_1:[Project_1_Domain@@Project_1_1. SBV...,NaN,NaN,NaN,NaN,01FB16ECS473,NaN,"Ethical Hacking by IIT Guwahati, Attended a we..."
428,0.95,0.86,NaN,CSE,7.52,4.50,DEBSOC(DEBATING SOCIETY) General Speaker | 201...,Accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[],{Project_1:[Project_1_Domain@@Project_1_1. SBV...,NaN,NaN,NaN,2.0,01FB16ECS473,NaN,"Ethical Hacking by IIT Guwahati, Attended a we..."
429,CGPA 10,0.958,NaN,CSE,9.54,15.82,NaN,LogMeIn,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,Fields of Interest\n● Cloud computing.\n● Full...,[Languages: C##C++##Python##R##Verilog##\nData...,{Project_1:[Project_1_Domain@@Project_1_1. Feb...,NaN,NaN,NaN,1.0,01FB16ECS481,NaN,NaN
430,92.6% (ICSE),91% (CBSE),Won 3rd Prize in GG Jam Game Development\nHack...,CSE,9.11,6.50,NaN,Wipro Turbo,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[C\nLimited Working Proficiency##\nC++\nLimite...,{Project_1:[Project_1_Domain@@Project_1_Propag...,NaN,NaN,NaN,2.0,01FB16ECS482,Volunteered for Science Quiz in EPSILON and Th...,NaN
431,CGPA: 10,93.33,"Runner-up at ’Tricks of Trade’, a game theory ...",CSE,9.57,19.27,NaN,Walmart Labs,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,[Python##C/C++##SQL## Verilog## Arduino## HTML...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,1.0,01FB16ECS483,NaN,NaN
432,CGPA: 10,93.33,"Runner-up at ’Tricks of Trade’, a game theory ...",CSE,9.57,NaN,NaN,Walmart Labs,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,[Python##C/C++##SQL## Verilog## Arduino## HTML...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,1.0,01FB16ECS483,NaN,NaN
433,CGPA: 10,93.33,"Runner-up at ’Tricks of Trade’, a game theory ...",CSE,9.57,0.00,NaN,Amazon,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,[Python##C/C++##SQL## Verilog## Arduino## HTML...,{Project_1:[Project_1_Domain@@Project_1_1. Hot...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,NaN,01FB16ECS483,NaN,NaN
434,10.00 GPA,0.95,NaN,CSE,9.15,26.40,NaN,Palo Alto Networks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"[C, Python## HTML## AngularJS## JavaScript##Ruby]",{Project_1:[Project_1_Domain@@Project_1_TextEd...,NaN,NaN,"MySql, Mongo, Rails, Postman, MathLab",1.0,01FB16ECS484,NaN,NaN
435,10 GPA,0.934,Best All Rounder Girl Student Award in SKCH-EC...,CSE,9.54,14.41,NaN,Lam Research,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,[C ## Javascript ## HTML ## CSS\n## Familiar- ...,{Project_1:[Project_1_Domain@@Project_1_File S...,NaN,Received Professor MRD Merit Scholarship Award...,NaN,1.0,01FB16ECS485,Peer Teaching classes for the subject Web Tech...,NaN

In [29]:
# 10th percentage and 12 percentage 
# convert everything to percent 10thPercentage, rename 10th marks
# null values -> mean
#df['10thMarks'] = 0
#df['10thMarks'] = df['10thPercentage'].map(lambda x: float(x)*9.5 if float(x) <=10 else float(x) )
#df['10thMarks'].fillna((df['10thMarks'].mean()), inplace=True)
#df['12thPercentage'].fillna((df['12thPercentage'].mean()), inplace=True)

In [14]:
df['Awards'].fillna((''),inplace = True)
df['Awards'] = df['Awards'].str.lower()
df['Languages'].fillna((''),inplace = True)
df['ProgLanguages'].fillna((''),inplace = True)

In [15]:
# awards, using keywords to extract

from nltk import ngrams
from sklearn.feature_extraction import text
stop = text.ENGLISH_STOP_WORDS

df["Awards"].apply(lambda words: ' '.join(word.lower() for word in words.split() if word not in stop))

vals = [y for x in df['Awards'] for y in x.split()]

n = [2,3]
a = pd.Series([y for x in n for y in ngrams(vals, x)]).value_counts()
a[:10]

(in, the)                    60
(of, the)                    49
(cnr, rao)                   40
(for, the)                   34
(rao, merit)                 32
(participated, in)           31
(cnr, rao, merit)            31
(pes, university)            30
(merit, scholarship)         29
(rao, merit, scholarship)    25
dtype: int64

In [16]:
#awards AWARDSNLPKEY column will contain only keywords seperated by ##
awards_keywords = ['distinction award','alcoding','hackerearth','olympiad','iisc','outstanding','hackathon','hackerrank','rotary club','iayp','intel','e-yantra','cnr','merit','robotics','machine learning','Data science','olympiad','quiz','microsoft','pesu i/o','centre innovation entrepreneur','model united nation','mun','math','chemistry','outgoing']
df['AwardsNLPkey'] = ''
for key in awards_keywords:
    for i in range(0, len(df)):
        if(df.iloc[i]['Awards'].find(key)!=-1):
            df.iloc[i, df.columns.get_loc('AwardsNLPkey')] =df.iloc[i, df.columns.get_loc('AwardsNLPkey')]+ key+'##'

In [17]:
#finding most occuring languages
pd.Series(' '.join(df['Languages']).lower().replace('\n','').replace(',',"##").replace(' ','##').split('##')).value_counts()[:20]

                 607
english          153
hindi            140
kannada          103
telugu            31
tamil             22
working           11
malayalam         10
bengali           10
marathi            8
and                7
konkani            7
proficiency)       7
-                  5
sanskrit           5
professional       5
german             4
(professional      3
c                  3
&                  3
dtype: int64

In [18]:
company_dict = {'Walmart Labs': 'walmart',
'TheMathCompany':'mathcompany',
'NXP Semiconductors': 'nxp',
'Intuit':'intuit',
'Citrix':'citrix',
'Novarties Healthcare':'novarties',
'Raramuri Technology':'raramuri',
'Optum':'optum',
'Cisco Systems':'cisco',
'Accenture':'accenture',
'Rupeek Fintech':'rupeek',
'Enquero Global':'enquero',
'AirAsia Technology Centre':['airasia','air asia'],
'Logmein':'logmein',
'Samsumg':'samsumg',
'Akamai Technologies':'akamai',
'IBM':'ibm',
'Mathworks':'mathworks',
'APMSE Software Services':'ampse',
'Wipro':'wipro',
'LAM Research':'lam',
'Goldman Sachs':'goldman',
'National Instruments':'national instruments',
'Amazon':'amazon',
'App Dynamics':['app dynamics','appdynamics'],
'Societe Generale':'societe',
'Morgan Stanley':'morgan',
'Pluribus Networks':'pluribus',
'Sandvine':'sandvine',
'Microsoft':'microsoft',
'PWC':['pwc','price waterhouse coopers'],
'Commvault':'commvault',
'Cure.Fit':['cure.fit','cure fit'],
'Epsilon':'epsilon',
'Hewlett-Packard Enterprise':['hewlett-packard enterprise','hewlett-packard','hpe','hp','hewlett packard'],
'Zscaler Softech':'zscaler',
'Analog Devices':'analog',
'Target':'target',
'SAP Labs':'sap',
'Gameskraft Technologies':'gameskraft',
'NCR Corporations':'ncr',
'Pensando Systems':'pensando',
'MakeMyTrip':'makemytrip',
'Flipkart':'flipkart',
'Siemens Healthneers':'siemens',
'L&T Technology Services':['l & t technology services','ltts','l&t'],
'Groww':'groww',
'Amagi':'amagi',
'Kickdrum Technologies':'kickdrum',
'SymphonyAI':'symphony',
'Deloitte':'deloitte',
'Cloudera':'cloudera',
'Couchbase':'couchbase',
'Amadeus Software Labs':'amadeus',
'Robert Bosch Engineering & Business Solutions':['bosch','rbei']
}

In [19]:
# making all company names uniform

df['CompanyName']= df['CompanyName'].str.lower()
df['CompanyName_New'] = ''
company_key_list = list(company_dict.keys()) 
company_val_list = list(company_dict.values()) 
for i in range(0, len(df)):
    for j in company_val_list:
        #print(j,type(j))
        if(pd.isnull(df.at[i,'CompanyName'])):
            df.iloc[i, df.columns.get_loc('CompanyName_New')] = np.nan
            #print("nan\n"+j)
            break
        elif(type(j) == str and df.iloc[i]['CompanyName'].find(j)!=-1):
            df.iloc[i, df.columns.get_loc('CompanyName_New')] = company_key_list[company_val_list.index(j)]
            #print('str '+j)
        elif(type(j)==list):
            #print("list outside ",j)
            for k in j:
                if(df.iloc[i]['CompanyName'].find(k)!=-1):
                    df.iloc[i, df.columns.get_loc('CompanyName_New')] = company_key_list[company_val_list.index(j)]
                    #print('list ',j)
                    break

In [20]:
#list(df.CompanyName_New.unique())
df

,10thPercentage,12thPercentage,Awards,Branch,CGPA,CTC,CoCurricularActivities,CompanyName,Courses,EmploymentType,...,PublicationDetails,Scholarships,SoftwareTools,TierLevel,USN,VolunteeringWork,Workshops,10thMarks,AwardsNLPkey,CompanyName_New
0,96.0,90.0,,CSE,9.68,18.00,NaN,walmart labs,"{'Core Courses': [{""{'Code': 'UE15CS101', 'Nam...",NaN,...,NaN,NaN,NaN,1.0,01FB15ECS019,NaN,NaN,0,,Walmart Labs
1,9.7,97.6,recipient of 6 distinction awards in all semes...,CSE,8.83,4.50,NaN,themathcompany,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,2.0,01FB16ECS002,NaN,NaN,0,distinction award##,TheMathCompany
2,9.7,97.6,recipient of 6 distinction awards in all semes...,CSE,8.83,12.15,NaN,nxp semiconductors,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Recipient of CNR Rao Scholarship in the 5th se...,NaN,1.0,01FB16ECS002,NaN,NaN,0,distinction award##,NXP Semiconductors
3,95.0,96.0,,CSE,9.27,0.00,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,NaN,NaN,01FB16ECS006,NaN,NaN,0,,Intuit
4,NaN,94.0,1st place at alcoding summer challenge (out of...,CSE,8.95,23.42,NaN,citrix r&d india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,"Prof MRD Scholarship for Academic Excellence, ...",Flask##Spring##MySQL##MongoDB,1.0,01FB16ECS012,NaN,NaN,0,alcoding##iisc##,Citrix
5,9.4,89.36,,CSE,8.78,8.36,Wildlife#Space#Cricket,novarties healthcare pvt. ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,Web Scraping ## Ajax##Flask##Photoshop## Light...,1.0,01FB16ECS015,NaN,NaN,0,,Novarties Healthcare
6,95.0,95.0,felicitated with distinction award for academi...,CSE,9.89,0.00,"Enthusiastic about travelling, photography, re...",cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,NaN,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",0,distinction award##olympiad##olympiad##math##,Cisco Systems
7,95.0,95.0,felicitated with distinction award for academi...,CSE,9.89,11.59,"Enthusiastic about travelling, photography, re...",optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,"{""Document embedding generation for cyber-aggr...",Received the Prof MRD Merit Scholarship for be...,MySQL##OpenCV##keras##scikit-learn##matplotlib...,1.0,01FB16ECS016,NaN,"Attended workshop on machine learning, image p...",0,distinction award##olympiad##olympiad##math##,Optum
8,94.2,89.2,bagged 13th rank in “hour storm #1” organized ...,CSE,9.39,29.00,NaN,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,"{""Document embedding generation for cyber-aggr...",Recipient of “CNR RAO Merit Scholarship” ##Bag...,SQL,1.0,01FB16ECS017,NaN,NaN,0,hackerearth##,Cisco Systems
9,94.5,94.5,awarded first class with distinction across al...,CSE,9.04,11.59,NaN,optum,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Recipient of Prof CNR RAO Merit Scholarship(20...,NodeJS##Flask,1.0,01FB16ECS018,NaN,NaN,0,,Optum
10,9.6,87.2,bet to code - secured third position in the co...,CSE,8.57,0.00,An active member of the Center For Innovation ...,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,"{"" Cassandra - Quality Of Service "":"" Benchmar...",NaN,Cassandra##Spring boot##MongoDB##Mesos##REST,NaN,01FB16ECS023,NaN,L1 CIE,0,iisc##,Intuit
11,95.0,89.4,,CSE,7.71,4.50,Football Player in College Team,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,Word##Excel##Powerpoint##Angular##Node.js##Exp...,2.0,01FB16ECS031,NaN,NaN,0,,Accenture
12,94.83,95.8,,CSE,9.90,25.16,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN,0,,Intuit
13,94.83,95.8,,CSE,9.90,NaN,NaN,intuit,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,University merit-based scholarship holder and ...,NaN,1.0,01FB16ECS035,NaN,NaN,0,,Intuit
14,10.0,90.6,,CSE,8.68,NaN,NaN,cisco,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN,0,,Cisco Systems
15,10.0,90.6,,CSE,8.68,29.00,NaN,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,1.0,01FB16ECS036,NaN,NaN,0,,Cisco Systems
16,8.2,85.6,,CSE,7.30,8.00,NaN,raramuri technology private limited (website: ...,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,1.0,01FB16ECS037,Organised and volunteered Events of Samarpana.,NaN,0,,Raramuri Technology
17,10.0,95.6,,CSE,9.22,16.00,NaN,rupeek fintech pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,Docker##AWS##GCP##SQL##MongoDB##SailJS##Hadoop...,1.0,01FB16ECS038,NaN,NaN,0,,Rupeek Fintech
18,85.6,97.2,,CSE,7.71,6.00,NaN,enquero global,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,"ReactJS, AWS basics, GCP basics, PostGreSQL, M...",2.0,01FB16ECS044,NaN,NaN,0,,Enquero Global
19,91.3,93.8,,CSE,8.64,25.16,NaN,intuit india product development center,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Received Prof. C N Rao Merit Scholarship durin...,MySQL,1.0,01FB16ECS050,NaN,NaN,0,,Intuit
20,10.0,90.8,,CSE,9.17,10.35,NaN,airasia technology centre india pvt. ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,1.0,01FB16ECS052,NaN,NaN,0,,AirAsia Technology Centre
21,10.0,90.8,,CSE,9.17,0.00,NaN,logmein,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,Prof. C.N.R. Rao Merit Scholarship,SQL,NaN,01FB16ECS052,NaN,NaN,0,,Logmein
22,NaN,93.0,,CSE,8.98,16.00,NaN,samsumg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,0,,Samsumg
23,NaN,93.0,,CSE,8.98,NaN,NaN,samsung r&d,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,{Recognition of Similar Scripted Language Char...,Prof. C.N.R. Rao Merit Scholarship,AWS##Hadoop##GCP##Zookeeper##Docker,1.0,01FB16ECS056,NaN,NaN,0,,
24,NaN,NaN,,CSE,9.52,16.30,NaN,akamai technologies,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,1.0,01FB16ECS069,NaN,NaN,0,,Akamai Technologies
25,90.0,91.0,,CSE,8.27,0.00,NaN,ibm india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,Mysql,NaN,01FB16ECS072,NaN,NaN,0,,IBM
26,90.0,91.0,,CSE,8.27,12.75,NaN,mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,Mysql,1.0,01FB16ECS072,NaN,NaN,0,,Mathworks
27,94.88,96.0,,CSE,8.73,8.00,NaN,apmse software services pvt. ltd. (eagleview),"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,1.0,01FB16ECS073,NaN,NaN,0,,
28,94.88,96.0,,CSE,8.73,6.50,NaN,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,JavaScript##PHP##MySQL##CSS##BigData##Machine ...,2.0,01FB16ECS073,NaN,NaN,0,,Accenture
29,NaN,NaN,institution of engineering and technology (iet...,CSE,9.72,12.75,"President of Mathematics Association 2015-16, ...",mathworks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,{Deep Learning on Binary Patterns for Face Rec...,CNR Rao Merit Scholarship winner for academic ...,Tensorflow##Pytorch##OpenCV##Scikitlearn##Matp...,1.0,01FB16ECS074,NaN,NaN,0,outstanding##,Mathworks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,NaN,0.896,,CSE,8.36,0.00,NaN,ge healthcare,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,HTML#### CSS#### Javascript#### SQL,NaN,01FB16ECS440,NaN,NaN,0,,
412,NaN,0.896,,CSE,8.36,6.50,NaN,wipro turbo,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,HTML#### CSS#### Javascript#### SQL,2.0,01FB16ECS440,NaN,NaN,0,,Wipro
413,0.903,0.943,,CSE,8.31,8.36,NaN,pwc india,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,"HTML####CSS####Javascript####PHP####,MYSQL",1.0,01FB16ECS441,NaN,"Computer Network Securit y - Wireshark, Kali L...",0,,PWC
414,9.8,85.4,1. 3 live applications on play-store (two game...,CSE,8.18,12.43,NaN,adobe systems india pvt ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,"Mr. Vinay,\nFounder & CxO,\nPiRuby, Bengaluru",NaN,"Cloud, Machine Learning, Big Data, Android, Un...",1.0,01FB16ECS444,NaN,NaN,0,,
415,9.8,85.4,1. 3 live applications on play-store (two game...,CSE,8.18,0.00,NaN,citrix r&d india pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,"Mr. Vinay,\nFounder & CxO,\nPiRuby, Bengaluru",NaN,"Cloud, Machine Learning, Big Data, Android, Un...",NaN,01FB16ECS444,NaN,NaN,0,,Citrix
416,0.9264,0.9675,,CSE,7.74,7.00,NaN,perfios,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,2.0,01FB16ECS446,NaN,NaN,0,,
417,NaN,NaN,awarded with multiple distinction certificate,CSE,7.48,7.00,NaN,perfios,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,2.0,01FB16ECS448,NaN,NaN,0,,
418,94,92.4,awarded prof. cnr rao merit scholarship for ac...,CSE,9.48,0.00,NaN,morgan stanley,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,NaN,NaN,01FB16ECS456,NaN,NaN,0,cnr##merit##,Morgan Stanley
419,94,92.4,awarded prof. cnr rao merit scholarship for ac...,CSE,9.48,12.43,NaN,adobe systems india pvt ltd.,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,1.0,01FB16ECS456,NaN,NaN,0,cnr##merit##,
420,0.9536,0.975,,CSE,9.06,0.00,NaN,amazon,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,SQLite####Postgres#### MongoDB,NaN,01FB16ECS459,NaN,NaN,0,,Amazon
421,0.9536,0.975,,CSE,9.06,10.30,NaN,hewlett packard enterprise,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,SQLite####Postgres#### MongoDB,1.0,01FB16ECS459,NaN,NaN,0,,Hewlett-Packard Enterprise
422,0.9536,0.975,,CSE,9.06,NaN,NaN,hpe,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,NaN,SQLite####Postgres#### MongoDB,1.0,01FB16ECS459,NaN,NaN,0,,Hewlett-Packard Enterprise
423,CGPA – 8.8,0.8,"organizer, samarasa, cultural fest, - managed...",CSE,7.68,6.00,NaN,abb global industries and services pvt ltd,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,● ICACCI 2019\n● Sketch to images using CNN an...,NaN,"MATLAB, TensorFlow, Keras\nWeb Applications: H...",2.0,01FB16ECS461,NaN,MEMBERSHIPS: IEEE Student Member- Responsible ...,0,hackathon##,
424,NaN,NaN,,CSE,7.71,6.50,NaN,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,2.0,01FB16ECS467,NaN,NaN,0,,Accenture
425,CGPA- 8.0,0.79,recipient of distinction scholarship in 2nd an...,CSE,8.13,4.00,NaN,kpmg,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,"Front-end: HTML, CSS, JavaScript####\nBack-end...",3.0,01FB16ECS468,NaN,NaN,0,quiz##,
426,8.8,80,,CSE,7.09,3.60,National level Basket Ball gold medalist\nPlay...,dxc technology,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,3.0,01FB16ECS472,NaN,NaN,0,,
427,0.95,0.86,,CSE,7.52,0.00,DEBSOC(DEBATING SOCIETY) General Speaker | 201...,mcafee,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,NaN,NaN,NaN,01FB16ECS473,NaN,"Ethical Hacking by IIT Guwahati, Attended a we...",0,,
428,0.95,0.86,,CSE,7.52,4.50,DEBSOC(DEBATING SOCIETY) General Speaker | 201...,accenture,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,2.0,01FB16ECS473,NaN,"Ethical Hacking by IIT Guwahati, Attended a we...",0,,Accenture
429,CGPA 10,0.958,,CSE,9.54,15.82,NaN,logmein,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,1.0,01FB16ECS481,NaN,NaN,0,,Logmein
430,92.6% (ICSE),91% (CBSE),won 3rd prize in gg jam game development\nhack...,CSE,9.11,6.50,NaN,wipro turbo,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,NaN,NaN,2.0,01FB16ECS482,Volunteered for Science Quiz in EPSILON and Th...,NaN,0,hackathon##cnr##merit##,Wipro
431,CGPA: 10,93.33,"runner-up at ’tricks of trade’, a game theory ...",CSE,9.57,19.27,NaN,walmart labs,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,1.0,01FB16ECS483,NaN,NaN,0,iisc##mun##,Walmart Labs
432,CGPA: 10,93.33,"runner-up at ’tricks of trade’, a game theory ...",CSE,9.57,NaN,NaN,walmart labs,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Summer Internship,...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,1.0,01FB16ECS483,NaN,NaN,0,iisc##mun##,Walmart Labs
433,CGPA: 10,93.33,"runner-up at ’tricks of trade’, a game theory ...",CSE,9.57,0.00,NaN,amazon,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,Recepient of C.N.R. Rao Merit Scholarship for ...,NaN,NaN,01FB16ECS483,NaN,NaN,0,iisc##mun##,Amazon
434,10.00 GPA,0.95,,CSE,9.15,26.40,NaN,palo alto networks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,"MySql, Mongo, Rails, Postman, MathLab",1.0,01FB16ECS484,NaN,NaN,0,,
435,10 GPA,0.934,best all rounder girl student award in skch-ec...,CSE,9.54,14.41,NaN,lam research,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,Received Professor MRD Merit Scholarship Award...,NaN,1.0,01FB16ECS485,Peer Teaching classes for the subject Web Tech...,NaN,0,,LAM Research
436,10 GPA,0.934,best all rounder girl student award in skch-ec...,CSE,9.54,6.50,NaN,schneider electric,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment only,...,NaN,Received Professor MRD Merit Scholarship Award...,NaN,2.0,01FB16ECS485,Peer Teaching classes for the subject Web Tech...,NaN,0,,
437,0.956,0.921,,CSE,8.92,0.00,NaN,mcafee,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Internship only,...,NaN,1.Was among the top 10% students in class X bo...,NaN,NaN,01FB16ECS487,NaN,NaN,0,,
438,0.9113,0.894,changed the branch from ece to cse based on gp...,CSE,9.05,11.00,• Took part in various coding competitions lik...,aruba networks,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,MySQL#### Postgres,1.0,01FB16ECS488,NaN,NaN,0,distinction award##cnr##merit##,
439,NaN,NaN,,CSE,8.47,29.00,NaN,cisco systems,"{'Core Courses': [{""{'Code': 'UE16CS101', 'Nam...",Full time employment + Internship (Mandatory),...,NaN,NaN,NaN,1.0,01FB16ECS489,NaN,NaN,0,,Cisco Systems
440,67.52,63.14,,CSE,7.38,4.00,NaN,accenture,"{'Core Courses': [{""{'Code': 'UE15CS201', 'Nam...",NaN,...,NaN,NaN,MYSQL####POSTRESQL#### MONGODB(intermediate),3.0,01FB16ECS719,NaN,NaN,0,,Accenture

In [21]:
#finding most occuring programming languages
pd.Series(' '.join(df['ProgLanguages']).lower().replace('\n','').replace(',',"##").replace('.',"##").replace(' ','##').split('##')).value_counts()[:15]

              1487
python         166
c++            113
html           113
c              112
[c             109
javascript     109
css             97
php             97
java            85
[]              57
r               41
and             41
data            40
]               39
dtype: int64

In [22]:
#finding most occuring software skills
df['SoftwareTools'].fillna((''),inplace = True)
pd.Series(' '.join(df['SoftwareTools']).lower().replace('\n','').replace(',',"##").replace('.',"##").replace(' ','##').split('##')).value_counts()[:20]

              1070
mysql           35
cloud           28
sql             26
aws             23
mongodb         22
hadoop          18
html            15
postgresql      15
flask           14
google          14
css             14
opencv          13
learning        13
linux           12
spark           12
android         12
javascript      12
web             12
machine         11
dtype: int64

In [25]:
#finding most occuring co curricular activities

df['CoCurricularActivities'].fillna((''),inplace = True)
stop = text.ENGLISH_STOP_WORDS
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
df['CoCurricularActivitiesNLP'] = df.CoCurricularActivities.str.replace("[^\w\s]", "").str.lower()

df['CoCurricularActivitiesNLP'] = df['CoCurricularActivitiesNLP'].apply(lambda x: ' '.join([item for item in x.split() if item not in stop]))

vals = [y for x in df['CoCurricularActivitiesNLP'] for y in x.split()]

n = [1]
a = pd.Series([y for x in n for y in ngrams(vals, x)]).value_counts()
a[:20]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\diyas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

(pes,)             56
(university,)      49
(member,)          39
(team,)            34
(participated,)    33
(school,)          33
(2017,)            32
(college,)         31
(fest,)            30
(club,)            28
(various,)         23
(events,)          23
(2018,)            21
(level,)           20
(competition,)     20
(science,)         19
(samarpana,)       19
(part,)            17
(organized,)       17
(scientist,)       17
dtype: int64

In [27]:
len(df)

441

In [28]:
df.to_csv(r'UpdatedMaster19Feb_NLP.csv')