In [1]:
'''
CGPA_15and16Batch_BTech_CS.xlsx
Elective_Grades_2015.xlsx
Elective_Grades_2016.xlsx
Grades_15_16_Batch_Students_Grades_AllSubjects.xlsx
SubjectList.xlsx

'''

'\nCGPA_15and16Batch_BTech_CS.xlsx\nElective_Grades_2015.xlsx\nElective_Grades_2016.xlsx\nGrades_15_16_Batch_Students_Grades_AllSubjects.xlsx\nSubjectList.xlsx\n\n'

In [2]:
import numpy as np

In [3]:
import pandas as pd

cgpa_df = pd.read_excel (r'CGPA_15and16Batch_BTech_CS.xlsx') 
elective15_df = pd.read_excel (r'Elective_Grades_2015.xlsx') 
elective16_df = pd.read_excel (r'Elective_Grades_2016.xlsx') 
grade_df = pd.read_csv (r'Grades_15_16_Batch_Students_Grades_AllSubjects.csv') 
sub_df = pd.read_excel (r'SubjectList.xlsx')

In [4]:
print(list(cgpa_df.columns))
print(list(elective15_df.columns))
print(list(elective16_df.columns))
print(list(grade_df.columns))
print(list(sub_df.columns))

[' StudentId', ' USN', ' TotalCredits', ' EarnedCredits', ' CGPA ']
['USN', ' SubjectCode', ' Grade']
['SRN', ' SubjectCode', ' Grade']
['USN', 'SubjectCode', 'SubjectName', 'Grade', 'Credits', 'EarnedCredit', 'GPS']
['SubjectCode', ' SubjectName', ' Credits']

In [5]:
cgpa_df.columns = cgpa_df.columns.str.replace(' ', '')
elective15_df.columns = elective15_df.columns.str.replace(' ', '')
elective16_df.columns = elective16_df.columns.str.replace(' ', '')
elective16_df.columns = elective16_df.columns.str.replace('SRN', 'USN')
grade_df.columns = grade_df.columns.str.replace(' ', '')
grade_df.columns = grade_df.columns.str.replace('EarnedCredit', 'EarnedCreditSubject')
sub_df.columns = sub_df.columns.str.replace(' ', '')

In [6]:
print(list(cgpa_df.columns))
print(list(elective15_df.columns))
print(list(elective16_df.columns))
print(list(grade_df.columns))
print(list(sub_df.columns))

['StudentId', 'USN', 'TotalCredits', 'EarnedCredits', 'CGPA']
['USN', 'SubjectCode', 'Grade']
['USN', 'SubjectCode', 'Grade']
['USN', 'SubjectCode', 'SubjectName', 'Grade', 'Credits', 'EarnedCreditSubject', 'GPS']
['SubjectCode', 'SubjectName', 'Credits']

In [7]:
#Mapping between studId and their USN

studID_usn_df = cgpa_df[['StudentId', 'USN']].copy()

In [8]:
#electives 2015 2016 concatenate

elective_df = pd.concat([elective15_df,elective16_df])
print(elective_df.shape, elective15_df.shape,elective16_df.shape)

(2989, 3) (2584, 3) (405, 3)

In [9]:
elective_df['elective'] = 'Elective Courses'
grade_df['elective'] = 'Core Courses'

In [10]:
elective_list= elective_df.SubjectCode.unique()

In [11]:
grade_df.loc[grade_df['SubjectCode'].isin(elective_list), 'elective'] = 'Y'

In [12]:
print(list(cgpa_df.columns))
print(list(elective15_df.columns))
print(list(elective16_df.columns))
print(list(elective_df.columns))
print(list(grade_df.columns))
print(list(sub_df.columns))

['StudentId', 'USN', 'TotalCredits', 'EarnedCredits', 'CGPA']
['USN', 'SubjectCode', 'Grade']
['USN', 'SubjectCode', 'Grade']
['USN', 'SubjectCode', 'Grade', 'elective']
['USN', 'SubjectCode', 'SubjectName', 'Grade', 'Credits', 'EarnedCreditSubject', 'GPS', 'elective']
['SubjectCode', 'SubjectName', 'Credits']

In [13]:
elective_df1 = pd.merge(elective_df, sub_df, on='SubjectCode', how = 'left')

In [14]:
print(elective_df1.shape,elective_df.shape,elective_df1.columns,elective_df1.Credits.unique())

(2989, 6) (2989, 4) Index(['USN', 'SubjectCode', 'Grade', 'elective', 'SubjectName', 'Credits'], dtype='object') [4 2 nan]

In [15]:
is_NaN = elective_df1.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = elective_df1[row_has_NaN]
print(rows_with_NaN)

               USN  SubjectCode Grade          elective SubjectName Credits
2558  01FM15ECS013    UE16CS615     A  Elective Courses         NaN     NaN
2559  01FM15ECS013    UE16CS624     A  Elective Courses         NaN     NaN
2872  01FB15ECS287  UESM19CS007     C  Elective Courses         NaN     NaN

In [16]:
grade_rev_df =  grade_df[grade_df.columns.difference(['EarnedCreditSubject', 'GPS'])]

In [17]:
print(grade_rev_df.shape)
print(grade_df.shape)
print(elective_df1.shape)

(131721, 6)
(131721, 8)
(2989, 6)

In [18]:
grade_overall_rev_df = pd.concat([grade_rev_df,elective_df1]) #both with 6 columns
grade_overall_df =pd.concat([grade_df,elective_df1]) #one 6 grade 8

C:\Users\rames\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.
C:\Users\rames\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [19]:
print(grade_overall_rev_df.shape)
print(grade_overall_df.shape)
grade_list = grade_overall_df.Grade.unique()
print(grade_list)

(134710, 6)
(134710, 8)
['C' 'A' 'F' 'D' 'E' 'AP' 'B' 'S' 'PASS' 'Pass' 'Not Pass' nan 'AB' 'D *'
 'PP' 'S+' 'P' 'CC' 'BC' 'DD' 'CD' 'BB' 'AA' 'W' 'E *' 'I']

In [20]:
rem_duplicate = grade_overall_rev_df.drop_duplicates(subset=['USN', 'SubjectCode'], keep='first')

In [21]:
print(rem_duplicate.shape)
print(grade_overall_rev_df.shape)
print(grade_overall_df.shape)

(131752, 6)
(134710, 6)
(134710, 8)

In [22]:
rem_duplicate1 = grade_overall_rev_df.drop_duplicates(subset=['USN', 'SubjectCode','Grade'], keep='first')

In [23]:
print(rem_duplicate1.shape)
print(grade_overall_rev_df.shape)
print(grade_overall_df.shape)

(131770, 6)
(134710, 6)
(134710, 8)

In [24]:
rem_duplicate1[~rem_duplicate1.apply(tuple,1).isin(rem_duplicate.apply(tuple,1))]

,Credits,Grade,SubjectCode,SubjectName,USN,elective
1713,4,W,UE15CS413,Content Management,01FB15ECS122,Elective Courses
2508,4,E,UE15CS323,Fuzzy Logic,01FB15ECS087,Elective Courses
2510,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS152,Elective Courses
2511,4,E,UE15CS344,Knowledge management,01FB15ECS154,Elective Courses
2515,4,E *,UE15CS344,Knowledge management,01FB15ECS368,Elective Courses
2518,4,D,UE15CS323,Fuzzy Logic,01FB16ECS717,Elective Courses
2519,4,C,UE15CS315,Multimedia Computing,01FB16ECS717,Elective Courses
2520,4,B,UE15CS315,Multimedia Computing,01FB16ECS724,Elective Courses
2521,4,D,UE15CS322,Data Analytics,01FB16ECS725,Elective Courses
2543,2,I,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses
2573,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS009,Elective Courses
2574,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS009,Elective Courses
2575,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS087,Elective Courses
2578,2,D,UE15CS452,Introduction to Business,01FB15ECS263,Elective Courses
2581,2,E,UE15CS452,Introduction to Business,01FB15ECS297,Elective Courses
2582,2,D,UE15CS451,Introduction to Software Testing,01FB15ECS360,Elective Courses
2583,2,E,UE15CS452,Introduction to Business,01FB15ECS368,Elective Courses
2861,2,E,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses

In [25]:
rem_duplicate1 = grade_overall_rev_df.drop_duplicates(subset=['USN', 'SubjectCode','Grade'], keep='first')

In [26]:
grade_overall_rev_df.sort_values(by=['USN'], inplace=True)

In [27]:
#grade_overall_rev_df['USN'] == '01FB16ECS724'
a = grade_overall_rev_df[grade_overall_rev_df['USN'] == '01FB16ECS724']
a[a['SubjectCode']=='UE15CS315']

,Credits,Grade,SubjectCode,SubjectName,USN,elective
2520,4,B,UE15CS315,Multimedia Computing,01FB16ECS724,Elective Courses
86435,4,F,UE15CS315,Multimedia Computing,01FB16ECS724,Y

In [28]:
dup_diff_grade = rem_duplicate1[rem_duplicate1.duplicated(subset=['USN','SubjectCode'], keep=False)].sort_values(by=['USN','SubjectCode'])

In [29]:
dup_diff_grade

,Credits,Grade,SubjectCode,SubjectName,USN,elective
3248,4,F,UE15CS335,Advanced Computer Networks,01FB15ECS009,Y
2573,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS009,Elective Courses
3260,4,F,UE15CS411,Enterprise Resource Planning,01FB15ECS009,Y
2574,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS009,Elective Courses
7759,4,F,UE15CS323,Fuzzy Logic,01FB15ECS087,Y
2508,4,E,UE15CS323,Fuzzy Logic,01FB15ECS087,Elective Courses
7772,4,F,UE15CS411,Enterprise Resource Planning,01FB15ECS087,Y
2575,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS087,Elective Courses
9620,4,F,UE15CS413,Content Management,01FB15ECS122,Y
1713,4,W,UE15CS413,Content Management,01FB15ECS122,Elective Courses
11373,4,F,UE15CS335,Advanced Computer Networks,01FB15ECS152,Y
2510,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS152,Elective Courses
11490,4,F,UE15CS344,Knowledge management,01FB15ECS154,Y
2511,4,E,UE15CS344,Knowledge management,01FB15ECS154,Elective Courses
17717,2,F,UE15CS452,Introduction to Business,01FB15ECS263,Y
2578,2,D,UE15CS452,Introduction to Business,01FB15ECS263,Elective Courses
18600,2,C,UE15CS452,Introduction to Business,01FB15ECS278,Y
2543,2,I,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses
2861,2,E,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses
19676,2,F,UE15CS452,Introduction to Business,01FB15ECS297,Y
2581,2,E,UE15CS452,Introduction to Business,01FB15ECS297,Elective Courses
23220,2,F,UE15CS451,Introduction to Software Testing,01FB15ECS360,Y
2582,2,D,UE15CS451,Introduction to Software Testing,01FB15ECS360,Elective Courses
23676,4,F,UE15CS344,Knowledge management,01FB15ECS368,Y
2515,4,E *,UE15CS344,Knowledge management,01FB15ECS368,Elective Courses
23689,2,F,UE15CS452,Introduction to Business,01FB15ECS368,Y
2583,2,E,UE15CS452,Introduction to Business,01FB15ECS368,Elective Courses
86119,4,F,UE15CS315,Multimedia Computing,01FB16ECS717,Y
2519,4,C,UE15CS315,Multimedia Computing,01FB16ECS717,Elective Courses
86120,4,F,UE15CS323,Fuzzy Logic,01FB16ECS717,Y
2518,4,D,UE15CS323,Fuzzy Logic,01FB16ECS717,Elective Courses
86435,4,F,UE15CS315,Multimedia Computing,01FB16ECS724,Y
2520,4,B,UE15CS315,Multimedia Computing,01FB16ECS724,Elective Courses
86481,4,F,UE15CS322,Data Analytics,01FB16ECS725,Y
2521,4,D,UE15CS322,Data Analytics,01FB16ECS725,Elective Courses

In [30]:
grade_remove_list = ['F', 'I']
removed_dupl = dup_diff_grade.loc[dup_diff_grade['Grade'].isin(grade_remove_list)]

In [31]:
removed_dupl.shape

(17, 6)

In [32]:
final_df = rem_duplicate1[~rem_duplicate1.apply(tuple,1).isin(removed_dupl.apply(tuple,1))]

In [33]:
print(final_df.shape, rem_duplicate1.shape)

(131753, 6) (131770, 6)

In [34]:
final_df[final_df.duplicated(subset=['USN','SubjectCode'], keep=False)].sort_values(by=['USN','SubjectCode'])

,Credits,Grade,SubjectCode,SubjectName,USN,elective
18600,2,C,UE15CS452,Introduction to Business,01FB15ECS278,Y
2861,2,E,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses

In [35]:
# for other duplications follow heirarchy all grade > W > F > I
#['S','A','B','C','D','E']
# after removing all F and I, sort based on USN, SubjectCode, Grade and keep only first occurence (highest grade)

#------Needs to be done ---------------------------------------------

In [36]:
final_df

,Credits,Grade,SubjectCode,SubjectName,USN,elective
0,4,C,UE15CS101,Introduction to Computing Using Python,01FB14ECS038,Core Courses
1,1,A,UE15CS102,Introduction to Computing Using Python Laboratory,01FB14ECS038,Core Courses
2,4,F,UE15CS151,Problem Solving with C,01FB14ECS038,Core Courses
3,1,D,UE15CS152,Problem Solving with C Laboratory,01FB14ECS038,Core Courses
4,4,E,UE15CS201,Digital Design and Computer Organization,01FB14ECS038,Core Courses
5,4,F,UE15CS202,Data Structures,01FB14ECS038,Core Courses
6,4,E,UE15CS203,Introduction to Data Sciences,01FB14ECS038,Core Courses
7,3,F,UE15CS204,Web Technologies-I,01FB14ECS038,Core Courses
8,4,F,UE15CS205,Discrete Mathematics and Logic,01FB14ECS038,Core Courses
9,1,C,UE15CS206,Digital Design & Computer Organization Labora...,01FB14ECS038,Core Courses
10,1,C,UE15CS207,Data Structures Laboratory,01FB14ECS038,Core Courses
11,1,C,UE15CS208,Web Technology- I Laboratory,01FB14ECS038,Core Courses
12,4,F,UE15CS251,Design and Analysis of Algorithms,01FB14ECS038,Core Courses
13,4,F,UE15CS252,Data Base Management Systems,01FB14ECS038,Core Courses
14,4,F,UE15CS253,Microprocessors & Computer Architecture,01FB14ECS038,Core Courses
15,3,F,UE15CS254,Theory of Computation,01FB14ECS038,Core Courses
16,1,F,UE15CS255,Design and Analysis of Algorithms Laboratory,01FB14ECS038,Core Courses
17,1,F,UE15CS256,Data Base Management Systems Laboratory,01FB14ECS038,Core Courses
18,1,F,UE15CS257,Microprocessor & Computer Architecture Labora...,01FB14ECS038,Core Courses
19,4,D,UE15CV101,Engineering Mechanics,01FB14ECS038,Core Courses
20,4,C,UE15CY101,Engineering Chemistry,01FB14ECS038,Core Courses
21,1,A,UE15CY102,Chemistry Laboratory,01FB14ECS038,Core Courses
22,4,E,UE15EC101,Basic Electronics Engineering,01FB14ECS038,Core Courses
23,4,F,UE15EE101,Basic Electrical Engineering,01FB14ECS038,Core Courses
24,0,AP,UE15HS101,Constitution of India and Professional Ethics,01FB14ECS038,Core Courses
25,0,AP,UE15HS102,Environmental Studies,01FB14ECS038,Core Courses
26,2,A,UE15JE101,Unified Engineering (JEDI),01FB14ECS038,Core Courses
27,4,E,UE15MA101,Engineering Mathematics - I,01FB14ECS038,Core Courses
28,4,F,UE15MA151,Engineering Mathematics - II,01FB14ECS038,Core Courses
29,4,F,UE15MA251,Linear Algebra & Its Applications,01FB14ECS038,Core Courses
...,...,...,...,...,...,...
2523,4,D,UE16CS342,Knowledge Management,01FB15ECS009,Elective Courses
2526,4,D,UE16CS346,Advanced Computer Networks,01FB15ECS087,Elective Courses
2558,NaN,A,UE16CS615,NaN,01FM15ECS013,Elective Courses
2559,NaN,A,UE16CS624,NaN,01FM15ECS013,Elective Courses
2573,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS009,Elective Courses
2574,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS009,Elective Courses
2575,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS087,Elective Courses
2578,2,D,UE15CS452,Introduction to Business,01FB15ECS263,Elective Courses
2581,2,E,UE15CS452,Introduction to Business,01FB15ECS297,Elective Courses
2582,2,D,UE15CS451,Introduction to Software Testing,01FB15ECS360,Elective Courses
2583,2,E,UE15CS452,Introduction to Business,01FB15ECS368,Elective Courses
2592,4,D,UE16CS313,Big Data,01FB15ECS009,Elective Courses
2682,4,D,UE16CS313,Big Data,01FB15ECS100,Elective Courses
2688,4,C,UE16CS313,Big Data,01FB15ECS105,Elective Courses
2689,4,E,UE16CS313,Big Data,01FB15ECS106,Elective Courses
2703,4,D,UE16CS313,Big Data,01FB15ECS122,Elective Courses
2704,4,D,UE16CS323,Fuzzy Logic,01FB15ECS122,Elective Courses
2705,4,F,UE16CS332,Storage Area Networks,01FB15ECS122,Elective Courses
2714,4,E,UE16CS313,Big Data,01FB15ECS130,Elective Courses
2749,4,B,UE16CS313,Big Data,01FB15ECS166,Elective Courses
2810,4,D,UE16CS313,Big Data,01FB15ECS230,Elective Courses
2845,4,C,UE16CS313,Big Data,01FB15ECS263,Elective Courses
2861,2,E,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses
2862,4,A,UE16CS332,Storage Area Networks,01FB15ECS278,Elective Courses
2872,NaN,C,UESM19CS007,NaN,01FB15ECS287,Elective Courses
2880,2,F,UE15CS452,Introduction to Business,01FB15ECS296,Elective Courses
2913,4,B,UE16CS313,Big Data,01FB15ECS329,Elective Courses
2943,4,C,UE16CS313,Big Data,01FB15ECS359,Elective Courses
2946,4,B,UE16CS313,Big Data,01FB15ECS368,Elective Courses
2988,4,D,UE16CS323,Fuzzy Logic,01FB16ECS728,Elective Courses

In [37]:
print(cgpa_df.shape)
usn_list_cs = cgpa_df.USN.unique()
print(usn_list_cs.size)

(886, 5)
886

In [38]:
usn_list = final_df.USN.unique()
print(usn_list.size)

2453

In [39]:
final_df_cs = final_df[final_df['USN'].isin(usn_list_cs)]

In [40]:
final_df_cs.shape
final_df_cs.USN.unique().size

886

In [41]:
final_df_cs['Course'] = final_df_cs.apply(lambda x: {"Code":x['SubjectCode'],"Name":x['SubjectName'],"Credits":x['Credits']},axis=1)

C:\Users\rames\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [42]:
final_df_cs['CourseGrade'] = final_df_cs.apply(lambda x: {str(x['Course']):x['Grade']},axis=1)

C:\Users\rames\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [43]:
final_df_cs

,Credits,Grade,SubjectCode,SubjectName,USN,elective,Course,CourseGrade
0,4,C,UE15CS101,Introduction to Computing Using Python,01FB14ECS038,Core Courses,"{'Code': 'UE15CS101', 'Name': 'Introduction to...","{'{'Code': 'UE15CS101', 'Name': 'Introduction ..."
1,1,A,UE15CS102,Introduction to Computing Using Python Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS102', 'Name': 'Introduction to...","{'{'Code': 'UE15CS102', 'Name': 'Introduction ..."
2,4,F,UE15CS151,Problem Solving with C,01FB14ECS038,Core Courses,"{'Code': 'UE15CS151', 'Name': 'Problem Solving...","{'{'Code': 'UE15CS151', 'Name': 'Problem Solvi..."
3,1,D,UE15CS152,Problem Solving with C Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS152', 'Name': 'Problem Solving...","{'{'Code': 'UE15CS152', 'Name': 'Problem Solvi..."
4,4,E,UE15CS201,Digital Design and Computer Organization,01FB14ECS038,Core Courses,"{'Code': 'UE15CS201', 'Name': 'Digital Design ...","{'{'Code': 'UE15CS201', 'Name': 'Digital Desig..."
5,4,F,UE15CS202,Data Structures,01FB14ECS038,Core Courses,"{'Code': 'UE15CS202', 'Name': 'Data Structures...","{'{'Code': 'UE15CS202', 'Name': 'Data Structur..."
6,4,E,UE15CS203,Introduction to Data Sciences,01FB14ECS038,Core Courses,"{'Code': 'UE15CS203', 'Name': 'Introduction to...","{'{'Code': 'UE15CS203', 'Name': 'Introduction ..."
7,3,F,UE15CS204,Web Technologies-I,01FB14ECS038,Core Courses,"{'Code': 'UE15CS204', 'Name': 'Web Technologie...","{'{'Code': 'UE15CS204', 'Name': 'Web Technolog..."
8,4,F,UE15CS205,Discrete Mathematics and Logic,01FB14ECS038,Core Courses,"{'Code': 'UE15CS205', 'Name': 'Discrete Mathem...","{'{'Code': 'UE15CS205', 'Name': 'Discrete Math..."
9,1,C,UE15CS206,Digital Design & Computer Organization Labora...,01FB14ECS038,Core Courses,"{'Code': 'UE15CS206', 'Name': 'Digital Design ...","{'{'Code': 'UE15CS206', 'Name': 'Digital Desig..."
10,1,C,UE15CS207,Data Structures Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS207', 'Name': 'Data Structures...","{'{'Code': 'UE15CS207', 'Name': 'Data Structur..."
11,1,C,UE15CS208,Web Technology- I Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS208', 'Name': 'Web Technology-...","{'{'Code': 'UE15CS208', 'Name': 'Web Technolog..."
12,4,F,UE15CS251,Design and Analysis of Algorithms,01FB14ECS038,Core Courses,"{'Code': 'UE15CS251', 'Name': 'Design and Anal...","{'{'Code': 'UE15CS251', 'Name': 'Design and An..."
13,4,F,UE15CS252,Data Base Management Systems,01FB14ECS038,Core Courses,"{'Code': 'UE15CS252', 'Name': 'Data Base Manag...","{'{'Code': 'UE15CS252', 'Name': 'Data Base Man..."
14,4,F,UE15CS253,Microprocessors & Computer Architecture,01FB14ECS038,Core Courses,"{'Code': 'UE15CS253', 'Name': 'Microprocessors...","{'{'Code': 'UE15CS253', 'Name': 'Microprocesso..."
15,3,F,UE15CS254,Theory of Computation,01FB14ECS038,Core Courses,"{'Code': 'UE15CS254', 'Name': 'Theory of Compu...","{'{'Code': 'UE15CS254', 'Name': 'Theory of Com..."
16,1,F,UE15CS255,Design and Analysis of Algorithms Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS255', 'Name': 'Design and Anal...","{'{'Code': 'UE15CS255', 'Name': 'Design and An..."
17,1,F,UE15CS256,Data Base Management Systems Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CS256', 'Name': 'Data Base Manag...","{'{'Code': 'UE15CS256', 'Name': 'Data Base Man..."
18,1,F,UE15CS257,Microprocessor & Computer Architecture Labora...,01FB14ECS038,Core Courses,"{'Code': 'UE15CS257', 'Name': 'Microprocessor ...","{'{'Code': 'UE15CS257', 'Name': 'Microprocesso..."
19,4,D,UE15CV101,Engineering Mechanics,01FB14ECS038,Core Courses,"{'Code': 'UE15CV101', 'Name': 'Engineering Mec...","{'{'Code': 'UE15CV101', 'Name': 'Engineering M..."
20,4,C,UE15CY101,Engineering Chemistry,01FB14ECS038,Core Courses,"{'Code': 'UE15CY101', 'Name': 'Engineering Che...","{'{'Code': 'UE15CY101', 'Name': 'Engineering C..."
21,1,A,UE15CY102,Chemistry Laboratory,01FB14ECS038,Core Courses,"{'Code': 'UE15CY102', 'Name': 'Chemistry Labor...","{'{'Code': 'UE15CY102', 'Name': 'Chemistry Lab..."
22,4,E,UE15EC101,Basic Electronics Engineering,01FB14ECS038,Core Courses,"{'Code': 'UE15EC101', 'Name': 'Basic Electroni...","{'{'Code': 'UE15EC101', 'Name': 'Basic Electro..."
23,4,F,UE15EE101,Basic Electrical Engineering,01FB14ECS038,Core Courses,"{'Code': 'UE15EE101', 'Name': 'Basic Electrica...","{'{'Code': 'UE15EE101', 'Name': 'Basic Electri..."
24,0,AP,UE15HS101,Constitution of India and Professional Ethics,01FB14ECS038,Core Courses,"{'Code': 'UE15HS101', 'Name': ' Constitution o...","{'{'Code': 'UE15HS101', 'Name': ' Constitution..."
25,0,AP,UE15HS102,Environmental Studies,01FB14ECS038,Core Courses,"{'Code': 'UE15HS102', 'Name': 'Environmental S...","{'{'Code': 'UE15HS102', 'Name': 'Environmental..."
26,2,A,UE15JE101,Unified Engineering (JEDI),01FB14ECS038,Core Courses,"{'Code': 'UE15JE101', 'Name': 'Unified Enginee...","{'{'Code': 'UE15JE101', 'Name': 'Unified Engin..."
27,4,E,UE15MA101,Engineering Mathematics - I,01FB14ECS038,Core Courses,"{'Code': 'UE15MA101', 'Name': 'Engineering Mat...","{'{'Code': 'UE15MA101', 'Name': 'Engineering M..."
28,4,F,UE15MA151,Engineering Mathematics - II,01FB14ECS038,Core Courses,"{'Code': 'UE15MA151', 'Name': 'Engineering Mat...","{'{'Code': 'UE15MA151', 'Name': 'Engineering M..."
29,4,F,UE15MA251,Linear Algebra & Its Applications,01FB14ECS038,Core Courses,"{'Code': 'UE15MA251', 'Name': 'Linear Algebra ...","{'{'Code': 'UE15MA251', 'Name': 'Linear Algebr..."
...,...,...,...,...,...,...,...,...
2520,4,B,UE15CS315,Multimedia Computing,01FB16ECS724,Elective Courses,"{'Code': 'UE15CS315', 'Name': 'Multimedia Comp...","{'{'Code': 'UE15CS315', 'Name': 'Multimedia Co..."
2521,4,D,UE15CS322,Data Analytics,01FB16ECS725,Elective Courses,"{'Code': 'UE15CS322', 'Name': 'Data Analytics'...","{'{'Code': 'UE15CS322', 'Name': 'Data Analytic..."
2523,4,D,UE16CS342,Knowledge Management,01FB15ECS009,Elective Courses,"{'Code': 'UE16CS342', 'Name': 'Knowledge Manag...","{'{'Code': 'UE16CS342', 'Name': 'Knowledge Man..."
2526,4,D,UE16CS346,Advanced Computer Networks,01FB15ECS087,Elective Courses,"{'Code': 'UE16CS346', 'Name': 'Advanced Comput...","{'{'Code': 'UE16CS346', 'Name': 'Advanced Comp..."
2573,4,E,UE15CS335,Advanced Computer Networks,01FB15ECS009,Elective Courses,"{'Code': 'UE15CS335', 'Name': 'Advanced Comput...","{'{'Code': 'UE15CS335', 'Name': 'Advanced Comp..."
2574,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS009,Elective Courses,"{'Code': 'UE15CS411', 'Name': 'Enterprise Reso...","{'{'Code': 'UE15CS411', 'Name': 'Enterprise Re..."
2575,4,C,UE15CS411,Enterprise Resource Planning,01FB15ECS087,Elective Courses,"{'Code': 'UE15CS411', 'Name': 'Enterprise Reso...","{'{'Code': 'UE15CS411', 'Name': 'Enterprise Re..."
2578,2,D,UE15CS452,Introduction to Business,01FB15ECS263,Elective Courses,"{'Code': 'UE15CS452', 'Name': 'Introduction to...","{'{'Code': 'UE15CS452', 'Name': 'Introduction ..."
2581,2,E,UE15CS452,Introduction to Business,01FB15ECS297,Elective Courses,"{'Code': 'UE15CS452', 'Name': 'Introduction to...","{'{'Code': 'UE15CS452', 'Name': 'Introduction ..."
2582,2,D,UE15CS451,Introduction to Software Testing,01FB15ECS360,Elective Courses,"{'Code': 'UE15CS451', 'Name': 'Introduction to...","{'{'Code': 'UE15CS451', 'Name': 'Introduction ..."
2583,2,E,UE15CS452,Introduction to Business,01FB15ECS368,Elective Courses,"{'Code': 'UE15CS452', 'Name': 'Introduction to...","{'{'Code': 'UE15CS452', 'Name': 'Introduction ..."
2592,4,D,UE16CS313,Big Data,01FB15ECS009,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2682,4,D,UE16CS313,Big Data,01FB15ECS100,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2688,4,C,UE16CS313,Big Data,01FB15ECS105,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2689,4,E,UE16CS313,Big Data,01FB15ECS106,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2703,4,D,UE16CS313,Big Data,01FB15ECS122,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2704,4,D,UE16CS323,Fuzzy Logic,01FB15ECS122,Elective Courses,"{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic', '...","{'{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic',..."
2705,4,F,UE16CS332,Storage Area Networks,01FB15ECS122,Elective Courses,"{'Code': 'UE16CS332', 'Name': 'Storage Area Ne...","{'{'Code': 'UE16CS332', 'Name': 'Storage Area ..."
2714,4,E,UE16CS313,Big Data,01FB15ECS130,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2749,4,B,UE16CS313,Big Data,01FB15ECS166,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2810,4,D,UE16CS313,Big Data,01FB15ECS230,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2845,4,C,UE16CS313,Big Data,01FB15ECS263,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2861,2,E,UE15CS452,Introduction to Business,01FB15ECS278,Elective Courses,"{'Code': 'UE15CS452', 'Name': 'Introduction to...","{'{'Code': 'UE15CS452', 'Name': 'Introduction ..."
2862,4,A,UE16CS332,Storage Area Networks,01FB15ECS278,Elective Courses,"{'Code': 'UE16CS332', 'Name': 'Storage Area Ne...","{'{'Code': 'UE16CS332', 'Name': 'Storage Area ..."
2872,NaN,C,UESM19CS007,NaN,01FB15ECS287,Elective Courses,"{'Code': 'UESM19CS007', 'Name': nan, 'Credits'...","{'{'Code': 'UESM19CS007', 'Name': nan, 'Credit..."
2880,2,F,UE15CS452,Introduction to Business,01FB15ECS296,Elective Courses,"{'Code': 'UE15CS452', 'Name': 'Introduction to...","{'{'Code': 'UE15CS452', 'Name': 'Introduction ..."
2913,4,B,UE16CS313,Big Data,01FB15ECS329,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2943,4,C,UE16CS313,Big Data,01FB15ECS359,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2946,4,B,UE16CS313,Big Data,01FB15ECS368,Elective Courses,"{'Code': 'UE16CS313', 'Name': 'Big Data', 'Cre...","{'{'Code': 'UE16CS313', 'Name': 'Big Data', 'C..."
2988,4,D,UE16CS323,Fuzzy Logic,01FB16ECS728,Elective Courses,"{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic', '...","{'{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic',..."

In [44]:
grouped = final_df_cs.groupby(['USN','elective'])
grouped_df = grouped.aggregate(lambda x: list(x))

In [45]:
grouped_df_reset = grouped_df.reset_index()
grouped_df_reset

,USN,elective,Credits,Grade,SubjectCode,SubjectName,Course,CourseGrade
0,01FB14ECS038,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[C, A, F, D, E, F, E, F, F, C, C, C, F, F, F, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
1,01FB14ECS900,Core Courses,"[4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, 4.0, 4.0, ...","[F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, ...","[UE14CS201, UE14CS203, UE14CS204, UE14CS206, U...","[Digital Design & Computer Organization, Stati...","[{'Code': 'UE14CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE14CS201', 'Name': 'Digital Desi..."
2,01FB15ECS001,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[C, B, B, B, A, A, C, B, A, A, S, A, A, A, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
3,01FB15ECS001,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, C, A, A, C, B, D]","[UE15CS314, UE15CS322, UE15CS335, UE15CS344, U...","[Big Data, Data Analytics, Advanced Computer N...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
4,01FB15ECS002,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[A, S, S, S, S, A, S, S, A, S, S, S, A, S, A, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
5,01FB15ECS002,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, S, S, A, A, A]","[UE15CS314, UE15CS325, UE15CS331, UE15CS341, U...","[Big Data, Artificial Intelligence, Computer N...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
6,01FB15ECS003,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[B, S, B, B, D, B, D, C, D, B, A, B, D, C, D, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
7,01FB15ECS003,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, A, A, D, S, B, B]","[UE15CS311, UE15CS325, UE15CS331, UE15CS348, U...","[Advanced Algorithms, Artificial Intelligence,...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
8,01FB15ECS004,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[B, S, A, A, B, B, C, B, B, A, S, B, A, A, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
9,01FB15ECS004,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, E, B, B, C, B]","[UE15CS314, UE15CS322, UE15CS331, UE15CS344, U...","[Big Data, Data Analytics, Computer Network Se...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
10,01FB15ECS005,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[A, A, A, B, B, A, B, B, S, S, S, A, A, B, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
11,01FB15ECS005,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, S, S, S, A, A, C]","[UE15CS314, UE15CS325, UE15CS333, UE15CS345, U...","[Big Data, Artificial Intelligence, Natural La...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
12,01FB15ECS006,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[B, B, B, B, S, S, B, B, A, S, S, S, A, A, A, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
13,01FB15ECS006,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, A, B, B, C, A, S]","[UE15CS314, UE15CS322, UE15CS331, UE15CS341, U...","[Big Data, Data Analytics, Computer Network Se...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
14,01FB15ECS008,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[B, A, A, B, A, A, B, C, C, A, S, A, B, C, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
15,01FB15ECS008,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, C, B, B, B, D]","[UE15CS311, UE15CS322, UE15CS334, UE15CS345, U...","[Advanced Algorithms, Data Analytics, High Per...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
16,01FB15ECS009,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[D, D, E, B, E, D, E, F, F, C, B, C, E, F, E, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
17,01FB15ECS009,Elective Courses,"[4, 4, 4, 4]","[D, E, C, D]","[UE16CS342, UE15CS335, UE15CS411, UE16CS313]","[Knowledge Management, Advanced Computer Netwo...","[{'Code': 'UE16CS342', 'Name': 'Knowledge Mana...","[{'{'Code': 'UE16CS342', 'Name': 'Knowledge Ma..."
18,01FB15ECS009,Y,"[4.0, 4.0, 4.0, 2.0]","[E, E, F, C]","[UE15CS315, UE15CS323, UE15CS344, UE15CS453]","[Multimedia Computing, Fuzzy Logic, Knowledge ...","[{'Code': 'UE15CS315', 'Name': 'Multimedia Com...","[{'{'Code': 'UE15CS315', 'Name': 'Multimedia C..."
19,01FB15ECS010,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[B, B, A, B, C, B, C, C, C, B, A, B, B, C, C, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
20,01FB15ECS010,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, C, B, B, B, B]","[UE15CS311, UE15CS322, UE15CS331, UE15CS344, U...","[Advanced Algorithms, Data Analytics, Computer...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
21,01FB15ECS011,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[F, B, E, C, F, E, D, E, E, B, C, C, D, C, C, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
22,01FB15ECS011,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, C, B, B, S, B]","[UE15CS315, UE15CS323, UE15CS335, UE15CS344, U...","[Multimedia Computing, Fuzzy Logic, Advanced C...","[{'Code': 'UE15CS315', 'Name': 'Multimedia Com...","[{'{'Code': 'UE15CS315', 'Name': 'Multimedia C..."
23,01FB15ECS012,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[C, A, C, B, B, B, B, C, B, B, A, B, A, C, C, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
24,01FB15ECS012,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, C, A, A, B, A, S]","[UE15CS314, UE15CS322, UE15CS335, UE15CS344, U...","[Big Data, Data Analytics, Advanced Computer N...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
25,01FB15ECS014,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[S, S, A, A, B, A, B, B, C, S, S, S, A, B, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
26,01FB15ECS014,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, C, A, A, B, A, B]","[UE15CS311, UE15CS322, UE15CS333, UE15CS345, U...","[Advanced Algorithms, Data Analytics, Natural ...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
27,01FB15ECS015,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[S, S, S, A, A, S, A, S, B, S, S, S, S, S, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
28,01FB15ECS015,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, S, A, S, S, S]","[UE15CS314, UE15CS322, UE15CS331, UE15CS341, U...","[Big Data, Data Analytics, Computer Network Se...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
29,01FB15ECS016,Core Courses,"[4.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 3.0, 4.0, ...","[A, B, A, A, B, A, B, B, A, S, S, S, S, A, B, ...","[UE15CS101, UE15CS102, UE15CS151, UE15CS152, U...","[Introduction to Computing Using Python , Intr...","[{'Code': 'UE15CS101', 'Name': 'Introduction t...","[{'{'Code': 'UE15CS101', 'Name': 'Introduction..."
...,...,...,...,...,...,...,...,...
1741,01FB16ECS716,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, D, C, A, C, C, D, C]","[UE15CS311, UE15CS321, UE15CS332, UE15CS344, U...","[Advanced Algorithms, Computer Graphics and Vi...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
1742,01FB16ECS717,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[E, E, F, F, F, C, B, C, F, D, E, F, D, D, B, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1743,01FB16ECS717,Elective Courses,"[4, 4, 4, 4]","[F, F, D, C]","[UE15CS314, UE15CS322, UE15CS323, UE15CS315]","[Big Data, Data Analytics, Fuzzy Logic, Multim...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1744,01FB16ECS717,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, S, C, C, B, D]","[UE15CS335, UE15CS344, UE15CS405, UE15CS413, U...","[Advanced Computer Networks, Knowledge managem...","[{'Code': 'UE15CS335', 'Name': 'Advanced Compu...","[{'{'Code': 'UE15CS335', 'Name': 'Advanced Com..."
1745,01FB16ECS718,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[D, D, E, C, E, C, A, C, D, D, E, F, C, B, B, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1746,01FB16ECS718,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, D, A, S, B, D, D]","[UE15CS315, UE15CS321, UE15CS335, UE15CS344, U...","[Multimedia Computing, Computer Graphics and V...","[{'Code': 'UE15CS315', 'Name': 'Multimedia Com...","[{'{'Code': 'UE15CS315', 'Name': 'Multimedia C..."
1747,01FB16ECS719,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[D, D, F, E, E, B, B, B, F, C, D, F, D, B, B, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1748,01FB16ECS719,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[E, D, S, S, B, B, C, C]","[UE15CS314, UE15CS322, UE15CS335, UE15CS344, U...","[Big Data, Data Analytics, Advanced Computer N...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1749,01FB16ECS720,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[C, B, E, C, C, A, A, B, D, B, D, C, C, A, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1750,01FB16ECS720,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[D, B, B, A, D, B, B]","[UE15CS311, UE15CS321, UE15CS335, UE15CS344, U...","[Advanced Algorithms, Computer Graphics and Vi...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
1751,01FB16ECS721,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[D, D, F, D, E, C, B, C, D, C, D, F, C, C, B, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1752,01FB16ECS721,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, D, B, S, B, A, C]","[UE15CS313, UE15CS321, UE15CS332, UE15CS344, U...","[Advanced Database Management Systems, Compute...","[{'Code': 'UE15CS313', 'Name': 'Advanced Datab...","[{'{'Code': 'UE15CS313', 'Name': 'Advanced Dat..."
1753,01FB16ECS722,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[C, C, E, B, D, B, S, A, C, C, C, C, A, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1754,01FB16ECS722,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[B, B, B, A, A, C, B, C]","[UE15CS311, UE15CS323, UE15CS331, UE15CS344, U...","[Advanced Algorithms, Fuzzy Logic, Computer Ne...","[{'Code': 'UE15CS311', 'Name': 'Advanced Algor...","[{'{'Code': 'UE15CS311', 'Name': 'Advanced Alg..."
1755,01FB16ECS723,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[C, C, E, C, D, C, B, B, C, C, C, E, B, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1756,01FB16ECS723,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[E, A, S, S, A, A, B, C]","[UE15CS314, UE15CS323, UE15CS335, UE15CS344, U...","[Big Data, Fuzzy Logic, Advanced Computer Netw...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1757,01FB16ECS724,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[D, D, F, F, E, C, B, B, D, D, C, E, C, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1758,01FB16ECS724,Elective Courses,"[4, 4]","[F, B]","[UE15CS314, UE15CS315]","[Big Data, Multimedia Computing]","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1759,01FB16ECS724,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, S, B, C, B, B, C]","[UE15CS323, UE15CS335, UE15CS344, UE15CS405, U...","[Fuzzy Logic, Advanced Computer Networks, Know...","[{'Code': 'UE15CS323', 'Name': 'Fuzzy Logic', ...","[{'{'Code': 'UE15CS323', 'Name': 'Fuzzy Logic'..."
1760,01FB16ECS725,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[C, A, D, B, B, B, A, A, D, C, E, E, B, A, B, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1761,01FB16ECS725,Elective Courses,[4],[D],[UE15CS322],[Data Analytics],"[{'Code': 'UE15CS322', 'Name': 'Data Analytics...","[{'{'Code': 'UE15CS322', 'Name': 'Data Analyti..."
1762,01FB16ECS725,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[C, A, A, B, D, C, C]","[UE15CS314, UE15CS331, UE15CS341, UE15CS405, U...","[Big Data, Computer Network Security, Cloud Co...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1763,01FB16ECS726,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[C, D, E, C, D, B, B, B, B, C, C, E, B, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1764,01FB16ECS726,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[A, D, S, A, A, B, B]","[UE15CS313, UE15CS321, UE15CS335, UE15CS344, U...","[Advanced Database Management Systems, Compute...","[{'Code': 'UE15CS313', 'Name': 'Advanced Datab...","[{'{'Code': 'UE15CS313', 'Name': 'Advanced Dat..."
1765,01FB16ECS727,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[E, C, F, D, E, B, B, B, C, C, C, D, C, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1766,01FB16ECS727,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[E, B, A, A, B, D, C]","[UE15CS314, UE15CS325, UE15CS335, UE15CS344, U...","[Big Data, Artificial Intelligence, Advanced C...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1767,01FB16ECS728,Core Courses,"[4.0, 4.0, 4.0, 3.0, 4.0, 1.0, 1.0, 1.0, 4.0, ...","[D, C, F, B, E, B, A, A, D, C, D, F, C, B, A, ...","[UE15CS201, UE15CS202, UE15CS203, UE15CS204, U...","[Digital Design and Computer Organization, Dat...","[{'Code': 'UE15CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE15CS201', 'Name': 'Digital Desi..."
1768,01FB16ECS728,Elective Courses,[4],[D],[UE16CS323],[Fuzzy Logic],"[{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic', ...","[{'{'Code': 'UE16CS323', 'Name': 'Fuzzy Logic'..."
1769,01FB16ECS728,Y,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 2.0]","[D, E, A, E, A, C, D, D]","[UE15CS314, UE15CS322, UE15CS335, UE15CS348, U...","[Big Data, Data Analytics, Advanced Computer N...","[{'Code': 'UE15CS314', 'Name': 'Big Data', 'Cr...","[{'{'Code': 'UE15CS314', 'Name': 'Big Data', '..."
1770,PES2201800770,Core Courses,"[4.0, 4.0, 4.0, 3.0, 3.0, 1.0, 1.0, 2.0]","[D, C, D, C, D, A, A, A]","[UE18CS201, UE18CS202, UE18CS203, UE18CS204, U...","[Digital Design & Computer Organization, Data ...","[{'Code': 'UE18CS201', 'Name': 'Digital Design...","[{'{'Code': 'UE18CS201', 'Name': 'Digital Desi..."

In [46]:
grades_total = grouped_df_reset.groupby('USN').apply(lambda x: dict(zip(x['elective'],x['CourseGrade'])))

In [47]:
type(grades_total)

pandas.core.series.Series

In [48]:
grades_total.to_frame().reset_index()
grades_total_final = grades_total.to_frame().reset_index().rename(columns = {0: 'Courses'}, inplace = False)

In [49]:
grades_total_final.to_csv(r'CoursesCS.csv', index = False)

In [50]:
merged_academic_cs = pd.merge(cgpa_df,grades_total_final , on=["USN"])

In [51]:
merged_academic_cs

,StudentId,USN,TotalCredits,EarnedCredits,CGPA,Courses
0,1079,01FB14ECS038,92.0,45.0,2.92,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
1,1323,01FB14ECS900,58.0,0.0,0.00,"{'Core Courses': [{'{'Code': 'UE14CS201', 'Nam..."
2,4253,01FB15ECS001,176.0,176.0,7.85,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
3,4254,01FB15ECS002,176.0,176.0,9.29,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
4,4255,01FB15ECS003,176.0,176.0,7.34,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
5,4256,01FB15ECS004,176.0,176.0,7.78,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
6,4257,01FB15ECS005,176.0,176.0,8.48,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
7,4258,01FB15ECS006,176.0,176.0,8.85,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
8,4260,01FB15ECS008,176.0,176.0,7.78,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
9,4261,01FB15ECS009,176.0,176.0,5.92,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
10,4262,01FB15ECS010,176.0,176.0,7.85,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
11,4263,01FB15ECS011,176.0,176.0,6.92,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
12,4264,01FB15ECS012,176.0,176.0,8.06,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
13,4266,01FB15ECS014,176.0,176.0,8.15,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
14,4267,01FB15ECS015,176.0,176.0,9.58,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
15,4268,01FB15ECS016,176.0,176.0,8.80,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
16,4269,01FB15ECS017,176.0,176.0,9.06,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
17,4270,01FB15ECS018,176.0,176.0,8.31,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
18,4271,01FB15ECS019,176.0,176.0,9.68,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
19,4272,01FB15ECS020,176.0,176.0,9.17,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
20,4273,01FB15ECS021,176.0,176.0,8.27,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
21,4274,01FB15ECS022,176.0,176.0,8.77,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
22,4275,01FB15ECS023,176.0,176.0,8.64,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
23,4276,01FB15ECS024,176.0,176.0,8.07,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
24,4277,01FB15ECS025,176.0,176.0,9.02,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
25,4278,01FB15ECS026,176.0,176.0,9.28,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
26,4279,01FB15ECS027,176.0,176.0,8.76,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
27,4280,01FB15ECS028,176.0,176.0,8.82,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
28,4281,01FB15ECS029,176.0,176.0,8.77,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
29,4282,01FB15ECS030,176.0,176.0,7.14,"{'Core Courses': [{'{'Code': 'UE15CS101', 'Nam..."
...,...,...,...,...,...,...
856,14657,01FB16ECS700,132.0,132.0,7.05,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
857,14658,01FB16ECS701,132.0,132.0,6.52,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
858,14659,01FB16ECS702,132.0,132.0,6.47,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
859,14660,01FB16ECS703,132.0,132.0,7.22,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
860,14661,01FB16ECS704,132.0,132.0,7.09,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
861,14662,01FB16ECS705,132.0,132.0,7.71,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
862,14663,01FB16ECS706,132.0,132.0,8.03,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
863,14664,01FB16ECS707,132.0,126.0,6.95,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
864,14665,01FB16ECS708,132.0,132.0,7.30,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
865,14666,01FB16ECS709,132.0,132.0,6.80,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
866,14667,01FB16ECS710,132.0,132.0,7.46,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
867,14668,01FB16ECS711,136.0,132.0,6.17,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
868,14669,01FB16ECS712,132.0,132.0,7.06,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
869,14670,01FB16ECS713,132.0,126.0,6.14,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
870,14671,01FB16ECS714,132.0,132.0,7.08,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
871,14672,01FB16ECS715,132.0,132.0,6.90,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
872,14673,01FB16ECS716,132.0,132.0,6.42,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
873,14674,01FB16ECS717,132.0,132.0,6.80,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
874,14675,01FB16ECS718,132.0,132.0,6.86,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
875,14676,01FB16ECS719,132.0,132.0,7.38,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
876,14677,01FB16ECS720,132.0,132.0,7.24,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
877,14678,01FB16ECS721,132.0,132.0,6.95,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
878,14679,01FB16ECS722,132.0,132.0,7.61,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
879,14680,01FB16ECS723,132.0,132.0,7.54,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
880,14681,01FB16ECS724,132.0,132.0,6.96,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
881,14682,01FB16ECS725,132.0,132.0,7.36,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
882,14683,01FB16ECS726,132.0,132.0,7.22,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
883,14684,01FB16ECS727,132.0,132.0,7.08,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
884,14685,01FB16ECS728,132.0,132.0,6.64,"{'Core Courses': [{'{'Code': 'UE15CS201', 'Nam..."
885,14231,PES2201800770,22.0,22.0,6.86,"{'Core Courses': [{'{'Code': 'UE18CS201', 'Nam..."

In [52]:
merged_academic_cs.to_csv(r'AcademicCombined_15_16_CS.csv', index = False)