In [1]:
%run Company2CoursesPreprocessing.ipynb

Enter path to master datasetMasterDatasetTemp_Preprocessed_Anonymized_small.csv
(180, 174)

In [2]:
# mapping the matrix into a 3 column dataframe=> using originalRatingsData from Company2CoursesPreprocessing.ipynb
# using result (sparse matrix from Company2CoursesPreprocessing.ipynb )
R = result.as_matrix()
company_ratings_mean = np.mean(R, axis = 1)
Ratings_demeaned = R - company_ratings_mean.reshape(-1, 1)

C:\Users\rames\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [3]:
# applying SVD ( will be useful when datapoints increase)
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(Ratings_demeaned, k = 50)
sigma = np.diag(sigma)
all_company_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + company_ratings_mean.reshape(-1, 1)

In [4]:
# getting the statistical predicted ratings, will be helpful in case certain courses were not mentioned
preds = pd.DataFrame(all_company_predicted_ratings, columns = result.columns)
preds.head()

,advanced_machine_learning,introduction_to_software_testing,principles_of_programming_languages,project_work,internship,unix_system_programming,digital_image_processing,data_analytics,computer_network_security,big_data,...,smart_materials,fluid_mechanics_and_machines,mechanics_of_fluids,mechanics_of_solids,thermodynamics_and_ic_engines,finite_element_modelling,hands_on_course_on_digital_system_simulation_and_synthesis,linear_system,embedded_programming_with_arduino,adaptive_system
0,0.000228,0.799647,0.800109,0.799960,0.799960,-0.001111,0.399957,0.000343,0.000882,0.399019,...,-0.000014,-0.000014,-0.000014,-0.000014,-0.000014,-0.000014,-0.000451,0.000209,0.000567,-0.000053
1,0.000088,0.001123,0.999956,1.000029,1.000029,0.002039,1.000051,-0.000501,-0.001463,0.000388,...,0.000021,0.000021,0.000021,0.000021,0.000021,0.000021,0.000536,-0.001266,-0.000781,-0.000500
2,0.002206,0.003937,0.273285,0.272595,0.272595,0.094562,0.454527,0.454171,0.179828,0.540435,...,0.000019,0.000019,0.000019,0.000019,0.000019,0.000019,-0.000224,-0.005836,-0.000348,-0.003314
3,-0.000072,0.000977,-0.000094,0.000043,0.000043,0.002049,0.714346,0.285170,0.141338,0.429410,...,0.000022,0.000022,0.000022,0.000022,0.000022,0.000022,0.000631,-0.000991,0.141990,-0.000312
4,0.001158,0.003330,0.000206,-0.000025,-0.000025,0.004394,0.000058,-0.000832,-0.002854,-0.001865,...,0.000036,0.000036,0.000036,0.000036,0.000036,0.000036,0.000595,-0.004414,-0.001186,-0.002220

In [5]:
def recommend_courses(preds, result, companyName, original_ratings, num_recommendations):
    
    # Get and sort the company's predictions
    company_row_number = result.index.get_loc(companyName)
    sorted_company_predictions = preds.iloc[company_row_number].sort_values(ascending=False)
    
    company_data = original_ratings[original_ratings.CompanyName_New == (companyName)]
    company_full = (company_data.sort_values(['Rating'], ascending=False))
    
    return company_full[:num_recommendations]

In [6]:
companyName = input("Enter Company Name (finally pick from dropdown)")
num_reco = int(input('How many courses?'))
recommend_courses(preds, result, companyName ,originalRatingsData, num_reco )

Enter Company Name (finally pick from dropdown)intuit
How many courses?15

     CompanyName_New                           CourseName  Rating
3937          intuit                computer_organization   1.000
3893          intuit             digital_image_processing   0.750
3894          intuit                       data_analytics   0.750
3896          intuit                             big_data   0.750
3897          intuit                 software_engineering   0.625
3889          intuit  principles_of_programming_languages   0.625
3890          intuit                         project_work   0.625
3891          intuit                           internship   0.625
3908          intuit         data_base_management_systems   0.625
3898          intuit  object_oriented_modeling_and_design   0.625
3900          intuit                     research_credits   0.500
3903          intuit                 research_methodology   0.500
3910          intuit              topics_in_deep_learning   0.500
3921          intuit                       design_pattern   0.500
3902          intuit          natural_language_processing   0.375