In [377]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image 
from pydot import graph_from_dot_data
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree, metrics
import ast

In [345]:
df= pd.read_csv(r"C:\Users\diyas\Downloads\MasterDatasetTemp_Preprocessed_Anonymized_small.csv")

In [346]:
#DT Model 9

#remove unnneccesary columns
df=df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'USN','10thPercentage','VolunteeringWork','EmploymentType', 'CoCurricularActivities', 'EventsParticipated', 'GeneralSkills','CTC','TierLevel','MinorAttended','Languages'])

#Target is Company name, 
#CTC and Tier can be mapped based on company name prediction

In [347]:
df.columns

Index(['10thMarks', '12thPercentage', 'Branch', 'CGPA', 'CourseName',
       'CourseGrade', 'CompanyName_New', 'NoofInternships',
       'InternshipProjectDomain', 'InternshipCompany', 'NoofProjects',
       'ProjectDetailDomain', 'ProgLanguages', 'Publication', 'ResearchDomain',
       'ScholarshipsKey', 'SoftwareTools', 'WorkshopsOrg', 'WorkshopsDomain',
       'AwardsNLPkey', 'ExternalCertificatesKey',
       'ExternalCertificatesDomain'],
      dtype='object')

In [348]:
#df['Languages'] = df['Languages'].replace({'\n':''}, regex=True)
df['ProgLanguages'] = df['ProgLanguages'].replace({'\n':''}, regex=True)
df['SoftwareTools'] = df['SoftwareTools'].replace({'\n':''}, regex=True)

In [349]:
#making into a columns into a list
df['ExternalCertificatesKey']=df['ExternalCertificatesKey'].str.split('##')
df['ExternalCertificatesDomain']=df['ExternalCertificatesDomain'].str.split('##')
df['AwardsNLPkey']=df['AwardsNLPkey'].str.split('##')
df['WorkshopsDomain']=df['WorkshopsDomain'].str.split('##')
df['WorkshopsOrg']=df['WorkshopsOrg'].str.split('##')
df['SoftwareTools']=df['SoftwareTools'].str.split('##')
df['ProgLanguages']=df['ProgLanguages'].str.split('##')
df['InternshipProjectDomain']=df['InternshipProjectDomain'].str.split('##')
df['ResearchDomain']=df['ResearchDomain'].str.split('##')
df['ProjectDetailDomain']=df['ProjectDetailDomain'].str.split('##')
df['InternshipCompany']=df['InternshipCompany'].str.split('##')
df['ScholarshipsKey']=df['ScholarshipsKey'].str.split('##')
df['Publication']=df['Publication'].str.split('##')
#df['Languages']=df['Languages'].str.split('##')

In [350]:
df.head()

,10thMarks,12thPercentage,Branch,CGPA,CourseName,CourseGrade,CompanyName_New,NoofInternships,InternshipProjectDomain,InternshipCompany,...,ProgLanguages,Publication,ResearchDomain,ScholarshipsKey,SoftwareTools,WorkshopsOrg,WorkshopsDomain,AwardsNLPkey,ExternalCertificatesKey,ExternalCertificatesDomain
0,96.000000,90.0,cse,9.68,"['introduction to computing using python ', 'i...","['s', 's', 's', 'a', 's', 's', 's', 's', 's', ...",walmart labs,NaN,NaN,NaN,...,"[python, c++, c]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[cryptography, ]"
1,92.150000,97.6,cse,8.83,"['introduction to computing using python', 'in...","['c', 'a', 'b', 'a', 's', 'a', 'b', 'a', 'a', ...",themathcompany,NaN,NaN,NaN,...,"[c, python, java, html, css, php, mysql]",NaN,NaN,"[cnr, ]",NaN,NaN,NaN,"[distinction award, ]",NaN,NaN
2,92.150000,97.6,cse,8.83,"['introduction to computing using python', 'in...","['c', 'a', 'b', 'a', 's', 'a', 'b', 'a', 'a', ...",nxp semiconductors,NaN,NaN,NaN,...,"[c, python, java, html, css, php, mysql]",NaN,NaN,"[cnr, ]",NaN,NaN,NaN,"[distinction award, ]",NaN,NaN
3,95.000000,96.0,cse,9.27,"['introduction to computing using python', 'in...","['b', 's', 'a', 'a', 's', 's', 'a', 'a', 'a', ...",intuit,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93.386967,94.0,cse,8.95,"['introduction to computing using python', 'in...","['b', 's', 'a', 'a', 'a', 's', 'a', 'b', 'a', ...",citrix,NaN,NaN,NaN,...,"[python, java, c, javascript, html, css, php]",NaN,NaN,"[mrd, ]","[flask, spring, mysql, mongodb]",NaN,NaN,"[alcoding, iisc, ]",NaN,NaN

In [351]:
['10thMarks', '12thPercentage', 'Branch', 'CGPA', 'CourseName',
       'CourseGrade', 'CompanyName_New', 'TierLevel', 'Languages',
       'MinorAttended', 'NoofInternships', 'InternshipProjectDomain',
       'InternshipCompany', 'NoofProjects', 'ProjectDetailDomain',
       'ProgLanguages', 'Publication', 'ResearchDomain', 'ScholarshipsKey',
       'SoftwareTools', 'WorkshopsOrg', 'WorkshopsDomain', 'AwardsNLPkey',
       'ExternalCertificatesKey', 'ExternalCertificatesDomain']


#converting to numerical
df['Branch'],_ = pd.factorize(df['Branch'])
df['CourseName'],_ = pd.factorize(df['CourseName'])
df['CourseGrade'],_ = pd.factorize(df['CourseGrade'])
df['CompanyName_New'],_ = pd.factorize(df['CompanyName_New'])
#df['InternshipCompany'],_ = pd.factorize(df['InternshipCompany'])
#df['Languages'],_ = pd.factorize(df['Languages'])
#df['InternshipProjectDomain'],_ = pd.factorize(df['InternshipProjectDomain'])

In [352]:
df.columns

Index(['10thMarks', '12thPercentage', 'Branch', 'CGPA', 'CourseName',
       'CourseGrade', 'CompanyName_New', 'NoofInternships',
       'InternshipProjectDomain', 'InternshipCompany', 'NoofProjects',
       'ProjectDetailDomain', 'ProgLanguages', 'Publication', 'ResearchDomain',
       'ScholarshipsKey', 'SoftwareTools', 'WorkshopsOrg', 'WorkshopsDomain',
       'AwardsNLPkey', 'ExternalCertificatesKey',
       'ExternalCertificatesDomain'],
      dtype='object')

In [333]:
#df=df.drop('InternshipProjectDomain', 1).join(df.InternshipProjectDomain.str.join('|').str.get_dummies())#

In [353]:
df=df.drop('InternshipCompany', 1).join(df.InternshipCompany.str.join('|').str.get_dummies())

In [354]:
df=df.drop('ProjectDetailDomain', 1).join(df.ProjectDetailDomain.str.join('|').str.get_dummies())

In [355]:
df=df.drop('ProgLanguages', 1).join(df.ProgLanguages.str.join('|').str.get_dummies())

In [356]:
df=df.drop('Publication', 1).join(df.Publication.str.join('|').str.get_dummies())

In [357]:
df=df.drop('ScholarshipsKey', 1).join(df.ScholarshipsKey.str.join('|').str.get_dummies())

In [358]:
#remove common software tools and prog lang
l=['css', 'django', 'html', 'javascript', 'mysql', 'nodejs', 'opencv','php', 'reactjs', 'sql']
for i,k in df.iterrows():
    n=[]
    if(df.SoftwareTools[i]!='' and type(df.SoftwareTools[i])!=float):
        for j in df.SoftwareTools[i]:
            if j not in l and type(j)!=float:
                n.append(j)
        df.SoftwareTools[i]=n
df=df.drop('SoftwareTools', 1).join(df.SoftwareTools.str.join('|').str.get_dummies())

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [ ]:
# no df=df.drop('ProgLanguages', 1).join(df.ProgLanguages.str.join('|').str.get_dummies())
#df=df.drop('ResearchDomain', 1).join(df.ResearchDomain.str.join('|').str.get_dummies())
#df=df.drop('Publication', 1).join(df.Publication.str.join('|').str.get_dummies())
#df=df.drop('ScholarshipsKey', 1).join(df.ScholarshipsKey.str.join('|').str.get_dummies())
#df=df.drop('SoftwareTools', 1).join(df.SoftwareTools.str.join('|').str.get_dummies())
# no df=df.drop('WorkshopsOrg', 1).join(df.WorkshopsOrg.str.join('|').str.get_dummies())
# no df=df.drop('WorkshopsDomain', 1).join(df.WorkshopsDomain.str.join('|').str.get_dummies())
# no df=df.drop('AwardsNLPkey', 1).join(df.AwardsNLPkey.str.join('|').str.get_dummies())
# no df=df.drop('ExternalCertificatesKey', 1).join(df.ExternalCertificatesKey.str.join('|').str.get_dummies())
# no df=df.drop('ExternalCertificatesDomain', 1).join(df.ExternalCertificatesDomain.str.join('|').str.get_dummies())

In [359]:
#remove a few common column
df=df.drop(columns=['InternshipProjectDomain','WorkshopsOrg', 'WorkshopsDomain','AwardsNLPkey', 'ExternalCertificatesKey','ExternalCertificatesDomain','ResearchDomain'])

In [360]:
p=list(df.columns)
p.remove('CompanyName_New')

In [361]:
df.head()

,10thMarks,12thPercentage,Branch,CGPA,CourseName,CourseGrade,CompanyName_New,NoofInternships,NoofProjects,adobe,...,spring boot,spring mvc,tensorflow,unity vuforia,unity3d,virtualization,web scraping,wireshark,word,zookeeper
0,96.000000,90.0,0,9.68,0,0,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,0
1,92.150000,97.6,0,8.83,1,1,1,NaN,7.0,0,...,0,0,0,0,0,0,0,0,0,0
2,92.150000,97.6,0,8.83,1,1,2,NaN,7.0,0,...,0,0,0,0,0,0,0,0,0,0
3,95.000000,96.0,0,9.27,2,2,3,NaN,4.0,0,...,0,0,0,0,0,0,0,0,0,0
4,93.386967,94.0,0,8.95,3,3,4,NaN,5.0,0,...,0,0,0,0,0,0,0,0,0,0

In [362]:
#dealing with NaN values 
df_temp=df
df_temp['NoofInternships'] = df_temp['NoofInternships'].fillna(0)
df_temp['NoofProjects'] = df_temp['NoofProjects'].fillna(0)
#selecting values where company is not empty
df_temp = df_temp[df_temp['CompanyName_New'].notna()]
#filling 10th and 12th with mean 
df_temp['10thMarks']=df_temp['10thMarks'].fillna((df_temp['10thMarks'].mean()), inplace=True)
df_temp['12thPercentage']=df_temp['12thPercentage'].fillna((df_temp['12thPercentage'].mean()), inplace=True)
df_temp['CGPA']=df['CGPA'].fillna((df_temp['CGPA'].mean()), inplace=True)

In [366]:
df_p=df
df_p.fillna(df_p.mean())

,10thMarks,12thPercentage,Branch,CGPA,CourseName,CourseGrade,CompanyName_New,NoofInternships,NoofProjects,adobe,...,spring boot,spring mvc,tensorflow,unity vuforia,unity3d,virtualization,web scraping,wireshark,word,zookeeper
0,96.000000,90.000000,0,9.68,0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,92.150000,97.600000,0,8.83,1,1,1,0.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
2,92.150000,97.600000,0,8.83,1,1,2,0.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
3,95.000000,96.000000,0,9.27,2,2,3,0.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
4,93.386967,94.000000,0,8.95,3,3,4,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
5,89.300000,89.360000,0,8.78,4,4,5,0.0,9.0,0,...,0,0,0,0,0,0,1,0,0,0
6,95.000000,95.000000,0,9.89,5,5,6,4.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
7,95.000000,95.000000,0,9.89,5,5,7,4.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
8,94.200000,89.200000,0,9.39,6,6,6,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
9,94.500000,94.500000,0,9.04,7,7,7,2.0,9.0,0,...,0,0,0,0,0,0,0,0,0,0
10,91.200000,87.200000,0,8.57,8,8,3,2.0,2.0,0,...,1,0,0,0,0,0,0,0,0,0
11,95.000000,89.400000,0,7.71,9,9,8,1.0,6.0,0,...,0,0,0,0,0,0,0,0,1,0
12,94.830000,95.800000,0,9.90,10,10,3,2.0,8.0,1,...,0,0,0,0,0,0,0,0,0,0
13,94.830000,95.800000,0,9.90,10,10,3,2.0,8.0,1,...,0,0,0,0,0,0,0,0,0,0
14,95.000000,90.600000,0,8.68,11,11,6,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
15,95.000000,90.600000,0,8.68,11,11,6,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
16,77.900000,85.600000,0,7.30,12,12,9,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
17,95.000000,95.600000,0,9.22,13,13,10,3.0,5.0,0,...,0,0,0,0,0,1,0,0,0,1
18,85.600000,97.200000,0,7.71,14,14,11,2.0,3.0,0,...,0,0,0,0,0,0,0,0,0,0
19,91.300000,93.800000,0,8.64,15,15,3,1.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
20,95.000000,90.800000,0,9.17,16,16,12,1.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
21,95.000000,90.800000,0,9.17,16,16,13,1.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
22,93.386967,93.000000,0,8.98,17,17,14,2.0,3.0,0,...,0,0,0,0,0,0,0,0,0,1
23,93.386967,93.000000,0,8.98,17,17,14,2.0,3.0,0,...,0,0,0,0,0,0,0,0,0,1
24,93.386967,92.664813,0,9.52,18,18,15,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
25,90.000000,91.000000,0,8.27,19,19,16,0.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
26,90.000000,91.000000,0,8.27,19,19,17,0.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
27,94.880000,96.000000,0,8.73,20,20,-1,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
28,94.880000,96.000000,0,8.73,20,20,8,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
29,93.386967,92.664813,0,9.72,21,21,17,3.0,4.0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,94.880000,92.700000,0,8.93,146,149,15,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
164,95.000000,97.700000,0,9.10,147,150,42,0.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
165,94.160000,94.500000,0,9.31,148,151,33,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
166,95.330000,93.200000,0,8.94,149,152,15,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
167,98.080000,95.500000,0,9.29,150,153,36,1.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
168,95.000000,96.400000,0,9.48,151,154,52,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
169,95.000000,95.200000,1,8.54,152,155,36,0.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
170,77.900000,95.800000,0,8.57,153,156,3,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
171,89.000000,98.000000,0,9.45,154,157,-1,0.0,3.0,0,...,0,0,0,0,0,0,0,0,0,0
172,97.280000,93.000000,1,8.69,155,158,53,2.0,6.0,0,...,0,0,0,0,0,0,0,0,0,0
173,95.660000,91.200000,0,9.63,156,159,22,3.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
174,95.000000,97.200000,0,9.38,157,160,20,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
175,96.000000,93.300000,0,8.17,158,161,4,1.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
176,89.300000,96.000000,1,6.84,159,162,-1,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
177,98.880000,97.500000,0,9.20,160,163,35,0.0,3.0,0,...,0,0,0,0,0,0,0,0,0,0
178,98.240000,94.500000,0,8.35,161,164,39,0.0,2.0,0,...,0,0,0,0,0,0,0,0,0,0
179,95.000000,93.000000,1,8.81,162,165,35,0.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
180,99.520000,97.700000,0,9.78,77,166,15,1.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
181,95.000000,97.200000,0,9.53,163,167,15,1.0,3.0,0,...,0,0,0,0,0,0,0,0,0,0
182,92.000000,97.500000,1,9.05,164,168,6,0.0,8.0,0,...,0,0,0,0,0,0,0,0,0,0
183,89.300000,92.200000,1,9.06,165,169,36,1.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0
184,93.100000,92.000000,0,8.61,166,170,32,0.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
185,99.000000,98.200000,0,9.77,167,171,52,1.0,3.0,0,...,0,0,0,0,0,0,0,0,0,0
186,98.240000,97.800000,1,8.95,168,172,32,0.0,2.0,0,...,0,0,0,0,0,0,0,0,0,0
187,91.200000,94.200000,1,9.04,169,173,6,2.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
188,98.540000,91.800000,0,8.50,170,174,36,0.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
189,91.200000,88.000000,1,8.26,171,175,35,1.0,9.0,0,...,0,0,0,0,0,0,0,0,0,0
190,94.560000,90.500000,2,8.07,172,176,-1,0.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
191,95.500000,94.700000,0,9.45,173,177,43,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
192,95.000000,90.200000,1,7.74,66,178,39,0.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0

In [367]:
df_p.head()

,10thMarks,12thPercentage,Branch,CGPA,CourseName,CourseGrade,CompanyName_New,NoofInternships,NoofProjects,adobe,...,spring boot,spring mvc,tensorflow,unity vuforia,unity3d,virtualization,web scraping,wireshark,word,zookeeper
0,96.000000,90.0,0,9.68,0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,92.150000,97.6,0,8.83,1,1,1,0.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
2,92.150000,97.6,0,8.83,1,1,2,0.0,7.0,0,...,0,0,0,0,0,0,0,0,0,0
3,95.000000,96.0,0,9.27,2,2,3,0.0,4.0,0,...,0,0,0,0,0,0,0,0,0,0
4,93.386967,94.0,0,8.95,3,3,4,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0

In [314]:
df_temp.shape

(193, 179)

In [372]:
X = df_p[p] # Features
y = df_p.CompanyName_New # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1) # 70% training and 30% test

In [373]:
# Create Decision Tree classifer 
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [374]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.15

In [375]:
dtree = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=100)
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))
print("Report : ", 
    classification_report(y_test, y_pred)) 
print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred))

Misclassified samples: 18
Accuracy: 0.10
Report :                precision    recall  f1-score   support

          -1       0.00      0.00      0.00         2
           0       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         1
          15       1.00      1.00      1.00         1
          17       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         2
          20       1.00      1.00      1.00         1
          22       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          30       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         2
          38       0.00      0.00      0.00         1
          39       0.00      0.00      0.00         1

    accuracy                           0.10        20
   macro avg       0.12      0.12      0.12        20
weighted avg       0.10      0.10      0.10        20

Confusion Matrix:  [[0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [379]:
#Model 10
#Adding courses 

data= pd.read_csv(r"C:\Users\diyas\Downloads\MasterDatasetTemp_Preprocessed_Anonymized_small.csv") 

#selecting only required columns
df8= data[['10thMarks', '12thPercentage','CGPA','NoofInternships','NoofProjects','Branch','TierLevel','ProjectDetailDomain','ProgLanguages','SoftwareTools','ScholarshipsKey','InternshipCompany','Publication','CourseName']]

#clean, preprocess missing values 
df8['NoofInternships'] = df8['NoofInternships'].fillna(0)
df8['TierLevel'] = df8['TierLevel'].fillna(0)
df8['NoofProjects'] = df8['NoofProjects'].fillna(0)
df8['Branch'],_ = pd.factorize(df8['Branch'])
df8=df8.fillna(df8.mean())
df8.CourseName=df8.CourseName.apply(lambda s: list(ast.literal_eval(s)))

#making seperate columns for research
df8['ProjectDetailDomain']=df8['ProjectDetailDomain'].str.split('##')
df8=df8.drop('ProjectDetailDomain', 1).join(df8.ProjectDetailDomain.str.join('|').str.get_dummies())

#making seperate columns for prog lang
df8['ProgLanguages'] = df8['ProgLanguages'].replace({'\n':''}, regex=True)
df8['ProgLanguages']=df8['ProgLanguages'].str.split('##')
df8=df8.drop('ProgLanguages', 1).join(df8.ProgLanguages.str.join('|').str.get_dummies())

#software tools
df8['SoftwareTools'] = df8['SoftwareTools'].replace({'\n':''}, regex=True)
df8['SoftwareTools']=df8['SoftwareTools'].str.split('##')

#remove common software tools and prog lang
l=['css', 'django', 'html', 'javascript', 'mysql', 'nodejs', 'opencv','php', 'reactjs', 'sql']
for i,k in df8.iterrows():
    n=[]
    if(df8.SoftwareTools[i]!='' and type(df8.SoftwareTools[i])!=float):
        for j in df8.SoftwareTools[i]:
            if j not in l and type(j)!=float:
                n.append(j)
        df8.SoftwareTools[i]=n
df8=df8.drop('SoftwareTools', 1).join(df8.SoftwareTools.str.join('|').str.get_dummies())

#course names
l1=['artificial intelligence', 'big data', 'blockchain', 'cloud computing',
       'compiler design', 'computer network security', 'computer networks',
       'data structures', 'digital design and computer organization',
       'digital signal processing', 'information security',
       'knowledge management', 'machine learning',
       'natural language processing', 'c++']
for i,k in df8.iterrows():
    n=[]
    if(df8.CourseName[i]!='' and type(df8.CourseName[i])!=float):
        for j in df8.CourseName[i]:
            if j not in l1 and type(j)!=float:
                n.append(j)
        df8.CourseName[i]=n
df8=df8.drop('CourseName', 1).join(df8.CourseName.str.join('|').str.get_dummies())

#scholoship and publications and internship company 
df8['ScholarshipsKey']=df8['ScholarshipsKey'].str.split('##')
df8['Publication']=df8['Publication'].str.split('##')
df8=df8.drop('Publication', 1).join(df8.Publication.str.join('|').str.get_dummies())
df8=df8.drop('ScholarshipsKey', 1).join(df8.ScholarshipsKey.str.join('|').str.get_dummies())
df8['InternshipCompany']=df8['InternshipCompany'].str.split('##')
df8=df8.drop('InternshipCompany', 1).join(df8.InternshipCompany.str.join('|').str.get_dummies())

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [380]:
#selecting target and features
p=list(df8.columns)
p.remove('TierLevel')
X = df8[p] # Features
y = df8.TierLevel # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

#Train model
dtree = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=100)
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))
print("Report : ", 
    classification_report(y_test, y_pred)) 
print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred))

Misclassified samples: 8
Accuracy: 0.79
Report :                precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         4
         1.0       0.87      0.96      0.91        27
         2.0       0.56      0.62      0.59         8

    accuracy                           0.79        39
   macro avg       0.47      0.53      0.50        39
weighted avg       0.71      0.79      0.75        39

Confusion Matrix:  [[ 0  1  3]
 [ 0 26  1]
 [ 0  3  5]]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [381]:
df8.shape

(193, 430)